/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.makeploy.common.dal.daointerface;

import com.onway.makeploy.common.dal.dataobject.CategoryDO;
import java.util.List;
import org.springframework.dao.DataAccessException;
import java.util.Date;
import java.util.Map;

/**
 * A dao interface provides methods to access database table <tt>makeploy_category</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/makeploy_category.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: CategoryDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public interface CategoryDAO {
	/**
	 *  Query DB table <tt>makeploy_category</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_category</tt>
	 *
	 *	@param fatherName
	 *	@return List<CategoryDO>
	 *	@throws DataAccessException
	 */	 
    public List<CategoryDO> selectTypeByFather(String fatherName) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_category</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_category</tt>
	 *
	 *	@param fatherName
	 *	@return List<CategoryDO>
	 *	@throws DataAccessException
	 */	 
    public List<CategoryDO> selectByFather(String fatherName) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_category</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_category</tt>
	 *
	 *	@param fatherName
	 *	@return CategoryDO
	 *	@throws DataAccessException
	 */	 
    public CategoryDO selectOneTypeByFather(String fatherName) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_category</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_category</tt>
	 *
	 *	@return List<String>
	 *	@throws DataAccessException
	 */	 
    public List<String> selectAllFather() throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_category</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_category</tt>
	 *
	 *	@return List<String>
	 *	@throws DataAccessException
	 */	 
    public List<String> selectOnlyFather() throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_category</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_category set memo='1', GMT_MODIFIED=CURRENT_TIMESTAMP where ((FATHER_NAME = ?) AND (memo = '2'))</tt>
	 *
	 *	@param fatherName
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteOnlyFather(String fatherName) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_category</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_category set FATHER_IMG=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (FATHER_NAME = ?)</tt>
	 *
	 *	@param fatherImg
	 *	@param fatherName
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateFatherIcon(String fatherImg, String fatherName) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_category</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_category set FATHER_NAME=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (FATHER_NAME = ?)</tt>
	 *
	 *	@param fatherName
	 *	@param fatherName2
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateFatherName(String fatherName, String fatherName2) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_category</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_category set MEMO='1', GMT_MODIFIED=CURRENT_TIMESTAMP where (FATHER_NAME = ?)</tt>
	 *
	 *	@param fatherName
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int delectFatherType(String fatherName) throws DataAccessException;

	/**
	 *  Insert one <tt>CategoryDO</tt> object to DB table <tt>makeploy_category</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into makeploy_category(ID,FATHER_NAME,CHILDREN_NAME,FATHER_IMG,CHILDREN_IMG,TYPE,CREATER,GMT_CREATE,MODIFIER,GMT_MODIFIED,MEMO) values (?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, ?, CURRENT_TIMESTAMP, ?)</tt>
	 *
	 *	@param category
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int addType(CategoryDO category) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_category</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_category set MEMO='1', GMT_MODIFIED=CURRENT_TIMESTAMP where (CHILDREN_NAME = ?)</tt>
	 *
	 *	@param childrenName
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteChirdType(String childrenName) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_category</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_category where (MEMO = '3')</tt>
	 *
	 *	@return List<CategoryDO>
	 *	@throws DataAccessException
	 */	 
    public List<CategoryDO> selectSize() throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_category</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_category where ((MEMO = '3') AND (FATHER_NAME = ?))</tt>
	 *
	 *	@param fatherName
	 *	@return CategoryDO
	 *	@throws DataAccessException
	 */	 
    public CategoryDO selectParamenterBySize(String fatherName) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_category</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_category set FATHER_IMG=?, GMT_MODIFIED=CURRENT_TIMESTAMP where ((MEMO = '3') AND (FATHER_NAME = ?))</tt>
	 *
	 *	@param fatherImg
	 *	@param fatherName
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateParamenterBySize(String fatherImg, String fatherName) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_category</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_category set TYPE=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (FATHER_NAME = ?)</tt>
	 *
	 *	@param type
	 *	@param fatherName
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateTypeToHomePage(String type, String fatherName) throws DataAccessException;

}