/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.makeploy.common.dal.daointerface;

import com.onway.makeploy.common.dal.dataobject.ProductDO;
import java.util.List;
import org.springframework.dao.DataAccessException;
import com.onway.common.lang.Money;
import java.util.Date;
import com.onway.makeploy.common.dal.dataobject.ShopShow;
import com.onway.common.lang.Money;
import java.util.Date;
import java.util.Map;

/**
 * A dao interface provides methods to access database table <tt>makeploy_product</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/makeploy_product.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: ProductDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public interface ProductDAO {
	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_product</tt>
	 *
	 *	@param userId
	 *	@param startRow
	 *	@param pageSize
	 *	@return List<ProductDO>
	 *	@throws DataAccessException
	 */	 
    public List<ProductDO> selectProductByUserId(String userId, Integer startRow, Integer pageSize) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_product</tt>
	 *
	 *	@param productNo
	 *	@return List<ProductDO>
	 *	@throws DataAccessException
	 */	 
    public List<ProductDO> selectProductByProNo(String productNo) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_product</tt>
	 *
	 *	@param shopId
	 *	@param startRow
	 *	@param pageSize
	 *	@return List<ProductDO>
	 *	@throws DataAccessException
	 */	 
    public List<ProductDO> selectProductByShopId(String shopId, Integer startRow, Integer pageSize) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_product</tt>
	 *
	 *	@return List<ProductDO>
	 *	@throws DataAccessException
	 */	 
    public List<ProductDO> selectNewProduct() throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_product</tt>
	 *
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int selectNewProductCount() throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_product where ((DEL_FLG = 0) AND (RECOMMEND_FLG = '3') AND (STATUS = 0) AND (CHECK_STATUS = '1'))</tt>
	 *
	 *	@return List<ProductDO>
	 *	@throws DataAccessException
	 */	 
    public List<ProductDO> selectTmiProduct() throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_product</tt>
	 *
	 *	@param shopId
	 *	@return List<ProductDO>
	 *	@throws DataAccessException
	 */	 
    public List<ProductDO> selectPartnerProduct(String shopId) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_product</tt>
	 *
	 *	@param shopId
	 *	@param productNo
	 *	@return ProductDO
	 *	@throws DataAccessException
	 */	 
    public ProductDO selectShopCartProduct(String shopId, String productNo) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_product</tt>
	 *
	 *	@param userId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int selectProductCountByUserId(String userId) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_product</tt>
	 *
	 *	@param shopId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int selectGoodsCountByShopId(String shopId) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_product</tt>
	 *
	 *	@param productNo
	 *	@param shopId
	 *	@return ProductDO
	 *	@throws DataAccessException
	 */	 
    public ProductDO selectProductByProductNo(String productNo, String shopId) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_product</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_product set DEL_FLG=1, GMT_MODIFIED=CURRENT_TIMESTAMP where ((USER_ID = ?) AND (PRODUCT_NO = ?))</tt>
	 *
	 *	@param userId
	 *	@param productNo
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteProductDelFlg2Zero(String userId, String productNo) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_product</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_product set SOLE_COUNT=?, GMT_MODIFIED=CURRENT_TIMESTAMP where ((SHOP_ID = ?) AND (PRODUCT_NO = ?))</tt>
	 *
	 *	@param soleCount
	 *	@param shopId
	 *	@param productNo
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int changeProductSellCount(int soleCount, String shopId, String productNo) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_product</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_product set STATUS=?, GMT_MODIFIED=CURRENT_TIMESTAMP where ((USER_ID = ?) AND (PRODUCT_NO = ?))</tt>
	 *
	 *	@param status
	 *	@param userId
	 *	@param productNo
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int OffTheShelfProduct(String status, String userId, String productNo) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_product</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_product set user_id=?</tt>
	 *
	 *	@param userId
	 *	@param stock
	 *	@param productNo
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateProductCount(String userId, Integer stock, String productNo) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_product</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_product set PRICE=?, GMT_MODIFIED=CURRENT_TIMESTAMP where ((SHOP_ID = ?) AND (USER_ID = ?) AND (PRODUCT_NO = ?))</tt>
	 *
	 *	@param price
	 *	@param shopId
	 *	@param userId
	 *	@param productNo
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateProductPrice(Money price, String shopId, String userId, String productNo) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_product</tt>
	 *
	 *	@param delflg
	 *	@return List<ShopShow>
	 *	@throws DataAccessException
	 */	 
    public List<ShopShow> selectShop(String delflg) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_product</tt>
	 *
	 *	@param productType
	 *	@param startRow
	 *	@param pageSize
	 *	@return List<ProductDO>
	 *	@throws DataAccessException
	 */	 
    public List<ProductDO> selectAllProduct(String productType, Integer startRow, Integer pageSize) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_product</tt>
	 *
	 *	@param productType
	 *	@param startRow
	 *	@param pageSize
	 *	@return List<ProductDO>
	 *	@throws DataAccessException
	 */	 
    public List<ProductDO> selectAllProductOrderByPrice(String productType, Integer startRow, Integer pageSize) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_product</tt>
	 *
	 *	@param productType
	 *	@param startRow
	 *	@param pageSize
	 *	@return List<ProductDO>
	 *	@throws DataAccessException
	 */	 
    public List<ProductDO> selectAllProductOrderByPriceDesc(String productType, Integer startRow, Integer pageSize) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select count(1) from makeploy_product</tt>
	 *
	 *	@param productType
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long selectAllProductCount(String productType) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_product</tt>
	 *
	 *	@param productType
	 *	@param startRow
	 *	@param pageSize
	 *	@return List<ProductDO>
	 *	@throws DataAccessException
	 */	 
    public List<ProductDO> selectproductByType(String productType, Integer startRow, Integer pageSize) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_product</tt>
	 *
	 *	@param children
	 *	@param startRow
	 *	@param pageSize
	 *	@return List<ProductDO>
	 *	@throws DataAccessException
	 */	 
    public List<ProductDO> selectChildrenByType(String children, Integer startRow, Integer pageSize) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_product</tt>
	 *
	 *	@param children
	 *	@param startRow
	 *	@param pageSize
	 *	@return List<ProductDO>
	 *	@throws DataAccessException
	 */	 
    public List<ProductDO> selectproductByTypeOrderByPrice(String children, Integer startRow, Integer pageSize) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_product</tt>
	 *
	 *	@param children
	 *	@param startRow
	 *	@param pageSize
	 *	@return List<ProductDO>
	 *	@throws DataAccessException
	 */	 
    public List<ProductDO> selectproductByTypeOrderByPriceDesc(String children, Integer startRow, Integer pageSize) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select count(1) from makeploy_product</tt>
	 *
	 *	@param children
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long selectproductCountByType(String children) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_product</tt>
	 *
	 *	@return List<ProductDO>
	 *	@throws DataAccessException
	 */	 
    public List<ProductDO> selectTeamGoProduct() throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_product</tt>
	 *
	 *	@param startRow
	 *	@param pageSize
	 *	@return List<ProductDO>
	 *	@throws DataAccessException
	 */	 
    public List<ProductDO> selectTeamGo(Integer startRow, Integer pageSize) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_product</tt>
	 *
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int selectTeamGoProductCount() throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_product</tt>
	 *
	 *	@param productName
	 *	@param startRow
	 *	@param pageSize
	 *	@return List<ProductDO>
	 *	@throws DataAccessException
	 */	 
    public List<ProductDO> search(String productName, Integer startRow, Integer pageSize) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_product</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_product set STOCK=?, GMT_MODIFIED=CURRENT_TIMESTAMP where ((PRODUCT_NO = ?) AND (SHOP_ID = ?))</tt>
	 *
	 *	@param stock
	 *	@param productNo
	 *	@param shopId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateStockByProductNo(int stock, String productNo, String shopId) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_product</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_product set NOW_PEOPLE=?, GMT_MODIFIED=CURRENT_TIMESTAMP where ((PRODUCT_NO = ?) AND (SHOP_ID = ?))</tt>
	 *
	 *	@param nowPeople
	 *	@param productNo
	 *	@param shopId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateNowPeopleByProNoAndShopId(int nowPeople, String productNo, String shopId) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_product</tt>
	 *
	 *	@param productName
	 *	@param startRow
	 *	@param pageSize
	 *	@return List<ProductDO>
	 *	@throws DataAccessException
	 */	 
    public List<ProductDO> searchLikeDesc(String productName, Integer startRow, Integer pageSize) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_product</tt>
	 *
	 *	@param productName
	 *	@param startRow
	 *	@param pageSize
	 *	@return List<ProductDO>
	 *	@throws DataAccessException
	 */	 
    public List<ProductDO> searchLikeAsc(String productName, Integer startRow, Integer pageSize) throws DataAccessException;

	/**
	 *  Insert one <tt>ProductDO</tt> object to DB table <tt>makeploy_product</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into makeploy_product(SHOP_ID,USER_ID,OTHER_TYPE,PRODUCT_NO,PRODUCT_NAME,PRODUCT_TYPE,PRODUCT_WEIGHT,CHILDREN,PRODUCT_OFF,PRICE,LUGGAGE,TEMPLATE_ID,USE_POINT,OLD_PRICE,CHECK_STATUS,STATUS,STOCK,PRODUCT_URL,DEL_FLG,PROPORTION_RETURN,PROPORTION_INTEGRAL,CREATER,GMT_CREATE,MODIFIER,GMT_MODIFIED,MEMO) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, ?, CURRENT_TIMESTAMP, ?)</tt>
	 *
	 *	@param product
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int insert(ProductDO product) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_product</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_product set PRODUCT_NAME=?, PRODUCT_TYPE=?, CHILDREN=?, PRODUCT_OFF=?, PRICE=?, LUGGAGE=?, OLD_PRICE=?, STOCK=?, PRODUCT_URL=?, GMT_MODIFIED=CURRENT_TIMESTAMP where ((SHOP_ID = ?) AND (PRODUCT_NO = ?))</tt>
	 *
	 *	@param productName
	 *	@param productType
	 *	@param children
	 *	@param productOff
	 *	@param price
	 *	@param luggage
	 *	@param oldPrice
	 *	@param stock
	 *	@param productUrl
	 *	@param shopId
	 *	@param productNo
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateProductInfo(String productName, String productType, String children, double productOff, Money price, Money luggage, Money oldPrice, int stock, String productUrl, String shopId, String productNo) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_product</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_product set PRODUCT_NAME=?, PRODUCT_TYPE=?, CHILDREN=?, PRICE=?, OLD_PRICE=?, LUGGAGE=?, STOCK=?, PRODUCT_URL=?, MEMO=?, GMT_MODIFIED=CURRENT_TIMESTAMP where ((SHOP_ID = ?) AND (PRODUCT_NO = ?))</tt>
	 *
	 *	@param productName
	 *	@param productType
	 *	@param children
	 *	@param price
	 *	@param oldPrice
	 *	@param luggage
	 *	@param stock
	 *	@param productUrl
	 *	@param memo
	 *	@param shopId
	 *	@param productNo
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int editProductInfo(String productName, String productType, String children, Money price, Money oldPrice, Money luggage, int stock, String productUrl, String memo, String shopId, String productNo) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_product</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_product set PRODUCT_NAME=?, PRODUCT_TYPE=?, CHILDREN=?, PRICE=?, OLD_PRICE=?, TEMPLATE_ID=?, STOCK=?, PRODUCT_URL=?, PRODUCT_WEIGHT=?, USE_POINT=?, GMT_MODIFIED=CURRENT_TIMESTAMP where ((SHOP_ID = ?) AND (PRODUCT_NO = ?))</tt>
	 *
	 *	@param productName
	 *	@param productType
	 *	@param children
	 *	@param price
	 *	@param oldPrice
	 *	@param templateId
	 *	@param stock
	 *	@param productUrl
	 *	@param productWeight
	 *	@param usePoint
	 *	@param shopId
	 *	@param productNo
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int editProduct(String productName, String productType, String children, Money price, Money oldPrice, String templateId, int stock, String productUrl, double productWeight, Money usePoint, String shopId, String productNo) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_product</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_product set STATUS=?, GMT_MODIFIED=CURRENT_TIMESTAMP where ((SHOP_ID = ?) AND (PRODUCT_NO = ?))</tt>
	 *
	 *	@param status
	 *	@param shopId
	 *	@param productNo
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateProductUpDownSTATUS(String status, String shopId, String productNo) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_product</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_product set STATUS=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (PRODUCT_NO = ?)</tt>
	 *
	 *	@param status
	 *	@param productNo
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateProductUpDownSTATUSByProNo(String status, String productNo) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_product</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_product set DEL_FLG=?, GMT_MODIFIED=CURRENT_TIMESTAMP where ((SHOP_ID = ?) AND (PRODUCT_NO = ?))</tt>
	 *
	 *	@param delFlg
	 *	@param shopId
	 *	@param productNo
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateProductDelflag(String delFlg, String shopId, String productNo) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_product</tt>
	 *
	 *	@param productName
	 *	@param startRow
	 *	@param pageSize
	 *	@return List<ProductDO>
	 *	@throws DataAccessException
	 */	 
    public List<ProductDO> searchLikeAll(String productName, Integer startRow, Integer pageSize) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select count(1) from makeploy_product</tt>
	 *
	 *	@param productName
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long searchLikeCount(String productName) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_product</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_product set RECOMMEND_FLG=?, GMT_MODIFIED=CURRENT_TIMESTAMP where ((SHOP_ID = ?) AND (PRODUCT_NO = ?))</tt>
	 *
	 *	@param recommendFlg
	 *	@param shopId
	 *	@param productNo
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateRecommendFlgByShopIdAndProductNo(String recommendFlg, String shopId, String productNo) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select count(1) from makeploy_product</tt>
	 *
	 *	@param shopId
	 *	@param productNo
	 *	@param flg
	 *	@param proName
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long countRecommendFlg(String shopId, String productNo, String flg, String proName) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_product</tt>
	 *
	 *	@param shopId
	 *	@param productNo
	 *	@param rflg
	 *	@param offent
	 *	@param limit
	 *	@param proName
	 *	@return List<ProductDO>
	 *	@throws DataAccessException
	 */	 
    public List<ProductDO> selectByRecommendFlg(String shopId, String productNo, String rflg, Integer offent, Integer limit, String proName) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_product</tt>
	 *
	 *	@param shopId
	 *	@param productName
	 *	@param productType
	 *	@param children
	 *	@param productNo
	 *	@param status
	 *	@param checkStatus
	 *	@param recommendFlg
	 *	@param priceMin
	 *	@param priceMax
	 *	@param startDate
	 *	@param endDate
	 *	@param startRow
	 *	@param pageSize
	 *	@return List<ProductDO>
	 *	@throws DataAccessException
	 */	 
    public List<ProductDO> selectProductByShopIdSearchBox(String shopId, String productName, String productType, String children, String productNo, String status, String checkStatus, String recommendFlg, Double priceMin, Double priceMax, Date startDate, Date endDate, Integer startRow, Integer pageSize) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_product</tt>
	 *
	 *	@param shopId
	 *	@param productName
	 *	@param productType
	 *	@param children
	 *	@param productNo
	 *	@param status
	 *	@param checkStatus
	 *	@param recommendFlg
	 *	@param priceMin
	 *	@param priceMax
	 *	@param startDate
	 *	@param endDate
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int selectCountProductByShopIdSearchBox(String shopId, String productName, String productType, String children, String productNo, String status, String checkStatus, String recommendFlg, Double priceMin, Double priceMax, Date startDate, Date endDate) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_product</tt>
	 *
	 *	@param shopId
	 *	@param productNo
	 *	@param startRow
	 *	@param pageSize
	 *	@return List<ProductDO>
	 *	@throws DataAccessException
	 */	 
    public List<ProductDO> selectUncheckProduct(String shopId, String productNo, Integer startRow, Integer pageSize) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select count(1) from makeploy_product</tt>
	 *
	 *	@param shopId
	 *	@param productNo
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int selectCountUncheckProduct(String shopId, String productNo) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_product</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_product set CHECK_STATUS=?, STATUS=?, PROPORTION_RETURN=?, PROPORTION_INTEGRAL=?, GMT_MODIFIED=CURRENT_TIMESTAMP where ((PRODUCT_NO = ?) AND (SHOP_ID = ?))</tt>
	 *
	 *	@param checkStatus
	 *	@param status
	 *	@param proportionReturn
	 *	@param proportionIntegral
	 *	@param productNo
	 *	@param shopId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateProductCheck(String checkStatus, String status, double proportionReturn, double proportionIntegral, String productNo, String shopId) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_product</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_product set NEED_PEOPLE=?, PRICE=?, PRODUCT_OFF=?, GMT_MODIFIED=CURRENT_TIMESTAMP where ((SHOP_ID = ?) AND (PRODUCT_NO = ?))</tt>
	 *
	 *	@param needPeople
	 *	@param price
	 *	@param productOff
	 *	@param shopId
	 *	@param productNo
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateNeedpeople(int needPeople, Money price, double productOff, String shopId, String productNo) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_product</tt>
	 *
	 *	@param userId
	 *	@return List<ProductDO>
	 *	@throws DataAccessException
	 */	 
    public List<ProductDO> searchShopId(String userId) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_product</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_product set PRODUCT_NO=?, PRODUCT_NAME=?, PRODUCT_TYPE=?, PRICE=?, PRODUCT_OFF=?, OLD_PRICE=?, LUGGAGE=?, RECOMMEND_FLG=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (SHOP_ID = ?)</tt>
	 *
	 *	@param productNo
	 *	@param productName
	 *	@param productType
	 *	@param price
	 *	@param productOff
	 *	@param oldPrice
	 *	@param luggage
	 *	@param recommendFlg
	 *	@param shopId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateProduct(String productNo, String productName, String productType, Money price, double productOff, Money oldPrice, Money luggage, String recommendFlg, String shopId) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_product</tt>
	 *
	 *	@param userId
	 *	@param offset
	 *	@param limit
	 *	@return List<ProductDO>
	 *	@throws DataAccessException
	 */	 
    public List<ProductDO> searchProductInfo(String userId, Integer offset, Integer limit) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_product where (RECOMMEND_FLG = ?)</tt>
	 *
	 *	@param recommendFlg
	 *	@return List<ProductDO>
	 *	@throws DataAccessException
	 */	 
    public List<ProductDO> searchParenter(String recommendFlg) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select count(1) from makeploy_product</tt>
	 *
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long total() throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_product</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_product set RECOMMEND_FLG=?, GMT_MODIFIED=CURRENT_TIMESTAMP where ((PRODUCT_NO = ?) AND (SHOP_ID = ?))</tt>
	 *
	 *	@param recommendFlg
	 *	@param productNo
	 *	@param shopId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateStatus(String recommendFlg, String productNo, String shopId) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_product where (PRODUCT_NO = ?)</tt>
	 *
	 *	@param productNo
	 *	@return ProductDO
	 *	@throws DataAccessException
	 */	 
    public ProductDO selectByShopIdSearch(String productNo) throws DataAccessException;

	/**
	 *  Insert one <tt>ProductDO</tt> object to DB table <tt>makeploy_product</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into makeploy_product(SHOP_ID,USER_ID,OTHER_TYPE,PRODUCT_NO,PRODUCT_NAME,PRODUCT_TYPE,PRODUCT_WEIGHT,CHILDREN,PRICE,PRODUCT_OFF,TEMPLATE_ID,OLD_PRICE,CHECK_STATUS,NEED_PEOPLE,NOW_PEOPLE,LUGGAGE,STATUS,STOCK,PRODUCT_URL,DEL_FLG,RECOMMEND_FLG,SOLE_COUNT,PROPORTION_RETURN,PROPORTION_INTEGRAL,CREATER,GMT_CREATE,MODIFIER,GMT_MODIFIED,MEMO) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, ?, CURRENT_TIMESTAMP, ?)</tt>
	 *
	 *	@param product
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int addPartnerPro(ProductDO product) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_product</tt>
	 *
	 *	@param shopId
	 *	@param proNo
	 *	@param proName
	 *	@param fatherType
	 *	@param childrenType
	 *	@param offset
	 *	@param limit
	 *	@return List<ProductDO>
	 *	@throws DataAccessException
	 */	 
    public List<ProductDO> selectShopProInfo(String shopId, String proNo, String proName, String fatherType, String childrenType, Integer offset, Integer limit) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_product</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select count(1) from makeploy_product</tt>
	 *
	 *	@param shopId
	 *	@param proNo
	 *	@param proName
	 *	@param fatherType
	 *	@param childrenType
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long proInfoCount(String shopId, String proNo, String proName, String fatherType, String childrenType) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_product</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_product set PRICE=?, NEED_PEOPLE=?, RECOMMEND_FLG=?, GMT_MODIFIED=CURRENT_TIMESTAMP where ((SHOP_ID = ?) AND (PRODUCT_NO = ?))</tt>
	 *
	 *	@param price
	 *	@param needPeople
	 *	@param recommendFlg
	 *	@param shopId
	 *	@param productNo
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateProPromotionTeamGo(Money price, int needPeople, String recommendFlg, String shopId, String productNo) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_product</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_product set PRICE=?, RECOMMEND_FLG=?, GMT_MODIFIED=CURRENT_TIMESTAMP where ((SHOP_ID = ?) AND (PRODUCT_NO = ?))</tt>
	 *
	 *	@param price
	 *	@param recommendFlg
	 *	@param shopId
	 *	@param productNo
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateProPromotionFirstTime(Money price, String recommendFlg, String shopId, String productNo) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_product</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_product set STATUS=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (SHOP_ID = ?)</tt>
	 *
	 *	@param status
	 *	@param shopId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int downProductOrderByShop(String status, String shopId) throws DataAccessException;

}