/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.makeploy.common.dal.daointerface;

import com.onway.makeploy.common.dal.dataobject.SequenceDO;
import org.springframework.dao.DataAccessException;
import java.util.Date;
import java.util.Map;

/**
 * A dao interface provides methods to access database table <tt>makeploy_sequence</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/makeploy_sequence.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: SequenceDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public interface SequenceDAO {
	/**
	 *  Insert one <tt>SequenceDO</tt> object to DB table <tt>makeploy_sequence</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into makeploy_sequence(biz_name,current_value,increment_value,GMT_CREATE,gmt_modified,PLATFORM_CODE) values (?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, "MERCHANT_PLATFORM")</tt>
	 *
	 *	@param sequence
	 *	@return String
	 *	@throws DataAccessException
	 */	 
    public String insert(SequenceDO sequence) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_sequence</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select biz_name, current_value, increment_value, GMT_CREATE, gmt_modified, PLATFORM_CODE from makeploy_sequence where (biz_name = ?)</tt>
	 *
	 *	@param bizName
	 *	@return SequenceDO
	 *	@throws DataAccessException
	 */	 
    public SequenceDO currentSequence(String bizName) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_sequence</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_sequence set current_value=(current_value + increment_value), gmt_modified=CURRENT_TIMESTAMP where (biz_name = ?)</tt>
	 *
	 *	@param bizName
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int nextSequence(String bizName) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>makeploy_sequence</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from makeploy_sequence where (biz_name = ?)</tt>
	 *
	 *	@param bizName
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteSequence(String bizName) throws DataAccessException;

}