/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.makeploy.common.dal.daointerface;

import com.onway.makeploy.common.dal.dataobject.ShopCommentDO;
import org.springframework.dao.DataAccessException;
import java.util.List;
import java.util.Date;
import java.util.Map;

/**
 * A dao interface provides methods to access database table <tt>makeploy_shop_comment</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/makeploy_shop_comment.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: ShopCommentDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public interface ShopCommentDAO {
	/**
	 *  Query DB table <tt>makeploy_shop_comment</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_shop_comment</tt>
	 *
	 *	@param shopId
	 *	@return ShopCommentDO
	 *	@throws DataAccessException
	 */	 
    public ShopCommentDO selectShopCommentInfoByShopId(String shopId) throws DataAccessException;

	/**
	 *  Insert one <tt>ShopCommentDO</tt> object to DB table <tt>makeploy_shop_comment</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into makeploy_shop_comment(SHOP_ID,PRODUCT_NO,USER_ID,PRODUCT_STAR,GMT_CREATE,GMT_MODIFIED) values (?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)</tt>
	 *
	 *	@param shopComment
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int insertSinglComments(ShopCommentDO shopComment) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_shop_comment</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_shop_comment</tt>
	 *
	 *	@param shopId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int selectAllStarCount(String shopId) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_shop_comment</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_shop_comment</tt>
	 *
	 *	@param shopId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int selectShopCommentCount(String shopId) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_shop_comment</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_shop_comment</tt>
	 *
	 *	@param shopId
	 *	@param orderId
	 *	@param offset
	 *	@param limit
	 *	@return List<ShopCommentDO>
	 *	@throws DataAccessException
	 */	 
    public List<ShopCommentDO> selectProductInfo(String shopId, String orderId, Integer offset, Integer limit) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_shop_comment</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select count(1) from makeploy_shop_comment</tt>
	 *
	 *	@param shopId
	 *	@param orderId
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long selectProductInfoCount(String shopId, String orderId) throws DataAccessException;

}