/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.makeploy.common.dal.daointerface;

import com.onway.makeploy.common.dal.dataobject.ShoppingCartDO;
import java.util.List;
import org.springframework.dao.DataAccessException;
import java.util.Date;
import java.util.Map;

/**
 * A dao interface provides methods to access database table <tt>makeploy_shopping_cart</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/makeploy_shopping_cart.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: ShoppingCartDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public interface ShoppingCartDAO {
	/**
	 *  Query DB table <tt>makeploy_shopping_cart</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_shopping_cart</tt>
	 *
	 *	@param userId
	 *	@param startRow
	 *	@param pageSize
	 *	@return List<ShoppingCartDO>
	 *	@throws DataAccessException
	 */	 
    public List<ShoppingCartDO> selectShoppingCartByUserId(String userId, Integer startRow, Integer pageSize) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_shopping_cart</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_shopping_cart</tt>
	 *
	 *	@param userId
	 *	@param productNo
	 *	@param shopId
	 *	@return ShoppingCartDO
	 *	@throws DataAccessException
	 */	 
    public ShoppingCartDO selectShoppingCartByUserIdAndProductNoAndShopId(String userId, String productNo, String shopId) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_shopping_cart</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_shopping_cart</tt>
	 *
	 *	@param userId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int selectShoppingCartCountByUserId(String userId) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_shopping_cart</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_shopping_cart set PRODUCT_COUNT=?, GMT_MODIFIED=CURRENT_TIMESTAMP where ((PRODUCT_NO = ?) AND (USER_ID = ?) AND (SHOP_ID = ?) AND (DEL_FLG = 0))</tt>
	 *
	 *	@param shoppingCart
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateShoppingCartInfo(ShoppingCartDO shoppingCart) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_shopping_cart</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_shopping_cart set DEL_FLG=1, GMT_MODIFIED=CURRENT_TIMESTAMP where ((PRODUCT_NO = ?) AND (USER_ID = ?) AND (SHOP_ID = ?))</tt>
	 *
	 *	@param shoppingCart
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteShoppingCartInfo(ShoppingCartDO shoppingCart) throws DataAccessException;

	/**
	 *  Insert one <tt>ShoppingCartDO</tt> object to DB table <tt>makeploy_shopping_cart</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into makeploy_shopping_cart(ID,USER_ID,PRODUCT_NO,SHOP_ID,PRICE,PRODUCT_COUNT,DEL_FLG,CREATER,GMT_CREATE,MODIFIER,GMT_MODIFIED,MEMO) values (?, ?, ?, ?, ?, ?, 0, ?, CURRENT_TIMESTAMP, ?, CURRENT_TIMESTAMP, ?)</tt>
	 *
	 *	@param shoppingCart
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int addShoppingCart(ShoppingCartDO shoppingCart) throws DataAccessException;

}