/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.makeploy.common.dal.daointerface;

import com.onway.makeploy.common.dal.dataobject.ShopDO;
import org.springframework.dao.DataAccessException;
import java.util.List;
import java.util.Date;
import java.util.Map;

/**
 * A dao interface provides methods to access database table <tt>makeploy_shop</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/makeploy_shop.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: ShopDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public interface ShopDAO {
	/**
	 *  Query DB table <tt>makeploy_shop</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_shop</tt>
	 *
	 *	@param userId
	 *	@return ShopDO
	 *	@throws DataAccessException
	 */	 
    public ShopDO selectShopInfoByUserId(String userId) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_shop</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_shop</tt>
	 *
	 *	@param userId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int selectShopCountByUserId(String userId) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_shop</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_shop</tt>
	 *
	 *	@param shopId
	 *	@return ShopDO
	 *	@throws DataAccessException
	 */	 
    public ShopDO selectShopInfoByShopId(String shopId) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_shop</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_shop</tt>
	 *
	 *	@param cell
	 *	@return ShopDO
	 *	@throws DataAccessException
	 */	 
    public ShopDO selectShopInfoByShopCell(String cell) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_shop</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_shop set SHOP_NAME=?, SHOP_DEC=?, CELL=?, SHOP_ADDR=?, SHOP_URL=?, INDUSTRY=?, LOACTION_X=?, LOACTION_Y=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (SHOP_ID = ?)</tt>
	 *
	 *	@param shop
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateShopInfo(ShopDO shop) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_shop</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_shop where (SHOP_ID = ?)</tt>
	 *
	 *	@param shopId
	 *	@return ShopDO
	 *	@throws DataAccessException
	 */	 
    public ShopDO selectShopByShopId(String shopId) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_shop</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_shop</tt>
	 *
	 *	@return List<ShopDO>
	 *	@throws DataAccessException
	 */	 
    public List<ShopDO> selectAllShop() throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_shop</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_shop</tt>
	 *
	 *	@return List<ShopDO>
	 *	@throws DataAccessException
	 */	 
    public List<ShopDO> selectUnionShopOnHome() throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_shop</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_shop</tt>
	 *
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int selectUnionShopCount() throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_shop</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_shop</tt>
	 *
	 *	@param startRow
	 *	@param pageSize
	 *	@return List<ShopDO>
	 *	@throws DataAccessException
	 */	 
    public List<ShopDO> selectUnionShop(Integer startRow, Integer pageSize) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_shop</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_shop</tt>
	 *
	 *	@param shopId
	 *	@param startRow
	 *	@param pageSize
	 *	@return List<ShopDO>
	 *	@throws DataAccessException
	 */	 
    public List<ShopDO> search(String shopId, Integer startRow, Integer pageSize) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_shop</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_shop where (USER_ID = ?)</tt>
	 *
	 *	@param userId
	 *	@return List<ShopDO>
	 *	@throws DataAccessException
	 */	 
    public List<ShopDO> selectShopListByUserId(String userId) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_shop</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_shop</tt>
	 *
	 *	@param shopId
	 *	@param cell
	 *	@param offent
	 *	@param limit
	 *	@return List<ShopDO>
	 *	@throws DataAccessException
	 */	 
    public List<ShopDO> selectShopIdandCellInfo(String shopId, String cell, Integer offent, Integer limit) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_shop</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_shop set UNION_FLG=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (SHOP_ID = ?)</tt>
	 *
	 *	@param unionFlg
	 *	@param shopId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateUnion(String unionFlg, String shopId) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_shop</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select count(1) from makeploy_shop</tt>
	 *
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long count() throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_shop</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_shop</tt>
	 *
	 *	@param shopId
	 *	@param userId
	 *	@param offset
	 *	@param limit
	 *	@param unionFlag
	 *	@param industry
	 *	@return List<ShopDO>
	 *	@throws DataAccessException
	 */	 
    public List<ShopDO> selectShopInfo(String shopId, String userId, Integer offset, Integer limit, String unionFlag, String industry) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_shop</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select count(1) from makeploy_shop</tt>
	 *
	 *	@param shopId
	 *	@param userId
	 *	@param unionflag
	 *	@param industry
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long selectShopInfoCount(String shopId, String userId, String unionflag, String industry) throws DataAccessException;

	/**
	 *  Insert one <tt>ShopDO</tt> object to DB table <tt>makeploy_shop</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into makeploy_shop(ID,SHOP_ID,USER_ID,UNION_FLG,SHOP_URL,DEL_FLAG,CREATER,GMT_CREATE,MODIFIER,GMT_MODIFIED,MEMO) values (?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, ?, CURRENT_TIMESTAMP, ?)</tt>
	 *
	 *	@param shop
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int creatNewShop(ShopDO shop) throws DataAccessException;

	/**
	 *  Insert one <tt>ShopDO</tt> object to DB table <tt>makeploy_shop</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into makeploy_shop(SHOP_ID,USER_ID,SHOP_NAME,CELL,SHOP_STAR,SHOP_DEC,SHOP_ADDR,UNION_FLG,DEL_FLAG,INDUSTRY,CREATER,GMT_CREATE,MODIFIER,GMT_MODIFIED,MEMO) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, ?, CURRENT_TIMESTAMP, ?)</tt>
	 *
	 *	@param shop
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int addCheckedShop(ShopDO shop) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_shop</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_shop</tt>
	 *
	 *	@return List<ShopDO>
	 *	@throws DataAccessException
	 */	 
    public List<ShopDO> selectAllShopInfo() throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_shop</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_shop set LOACTION_X=?, LOACTION_Y=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (SHOP_ID = ?)</tt>
	 *
	 *	@param loactionX
	 *	@param loactionY
	 *	@param shopId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateShopLngAndLat(double loactionX, double loactionY, String shopId) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_shop</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_shop set CREATER=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (SHOP_ID = ?)</tt>
	 *
	 *	@param creater
	 *	@param shopId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateShopLevel(String creater, String shopId) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_shop</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_shop set SHOP_UP=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (SHOP_ID = ?)</tt>
	 *
	 *	@param shopUp
	 *	@param shopId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int setShopUp(String shopUp, String shopId) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_shop</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_shop set SELL_COUNT=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (SHOP_ID = ?)</tt>
	 *
	 *	@param sellCount
	 *	@param shopId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int changeShopCellCount(int sellCount, String shopId) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_shop</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_shop set DEL_FLAG=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (SHOP_ID = ?)</tt>
	 *
	 *	@param delFlag
	 *	@param shopId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int changeShopDelFlag(String delFlag, String shopId) throws DataAccessException;

}