/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.makeploy.common.dal.daointerface;

import com.onway.makeploy.common.dal.dataobject.ShopCheckDO;
import java.util.List;
import org.springframework.dao.DataAccessException;
import java.util.Date;
import java.util.Map;

/**
 * A dao interface provides methods to access database table <tt>makeploy_shop_check</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/makeploy_shop_check.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: ShopCheckDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public interface ShopCheckDAO {
	/**
	 *  Query DB table <tt>makeploy_shop_check</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_shop_check</tt>
	 *
	 *	@param shopName
	 *	@param shopCell
	 *	@param flag
	 *	@param offset
	 *	@param limit
	 *	@return List<ShopCheckDO>
	 *	@throws DataAccessException
	 */	 
    public List<ShopCheckDO> selectShopCheckStatus(String shopName, String shopCell, String flag, Integer offset, Integer limit) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_shop_check</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select count(1) from makeploy_shop_check</tt>
	 *
	 *	@param shopName
	 *	@param shopCell
	 *	@param flag
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int countitmes(String shopName, String shopCell, String flag) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_shop_check</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_shop_check set CHECK_STATUS=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (SHOP_ID = ?)</tt>
	 *
	 *	@param checkStatus
	 *	@param shopId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateCheckStatusByshopId(String checkStatus, String shopId) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_shop_check</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_shop_check set CHECK_STATUS=?, GMT_MODIFIED=CURRENT_TIMESTAMP, MEMO=? where (SHOP_ID = ?)</tt>
	 *
	 *	@param checkStatus
	 *	@param memo
	 *	@param shopId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updatePartnerCheckStatusByshopId(String checkStatus, String memo, String shopId) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_shop_check</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_shop_check set CHECK_STATUS=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (USER_ID = ?)</tt>
	 *
	 *	@param checkStatus
	 *	@param userId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateCheckStatusByUserId(String checkStatus, String userId) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_shop_check</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_shop_check set CHECK_STATUS=?, APPLY_TYPE=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (USER_ID = ?)</tt>
	 *
	 *	@param checkStatus
	 *	@param applyType
	 *	@param userId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int changeApplytype(String checkStatus, String applyType, String userId) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_shop_check</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_shop_check set CHECK_STATUS=?, APPLY_TYPE=?, GMT_MODIFIED=CURRENT_TIMESTAMP, MEMO=? where (USER_ID = ?)</tt>
	 *
	 *	@param checkStatus
	 *	@param applyType
	 *	@param memo
	 *	@param userId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int changePartnerApplytype(String checkStatus, String applyType, String memo, String userId) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_shop_check</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_shop_check where (SHOP_ID = ?)</tt>
	 *
	 *	@param shopId
	 *	@return ShopCheckDO
	 *	@throws DataAccessException
	 */	 
    public ShopCheckDO selectByShopId(String shopId) throws DataAccessException;

	/**
	 *  Query DB table <tt>makeploy_shop_check</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_shop_check</tt>
	 *
	 *	@param userId
	 *	@param applyType
	 *	@param checkStatus
	 *	@return ShopCheckDO
	 *	@throws DataAccessException
	 */	 
    public ShopCheckDO selectByUserIdApplyType(String userId, String applyType, String checkStatus) throws DataAccessException;

	/**
	 *  Insert one <tt>ShopCheckDO</tt> object to DB table <tt>makeploy_shop_check</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into makeploy_shop_check(ID,SHOP_ID,USER_NAME,USER_ID,SHOP_NAME,USER_CELL,SHOP_CELL,SHOP_DEC,SHOP_ADDR,CARD_ADDR,NOW_ADDR,SHOP_URL,USER_JOB,CHECK_STATUS,APPLY_TYPE,CREATER,GMT_CREATE,MODIFIER,GMT_MODIFIED,MEMO) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, ?, CURRENT_TIMESTAMP, ?)</tt>
	 *
	 *	@param shopCheck
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int addCheckedPartner(ShopCheckDO shopCheck) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_shop_check</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_shop_check set SHOP_NAME=?, SHOP_CELL=?, SHOP_DEC=?, SHOP_ADDR=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (SHOP_ID = ?)</tt>
	 *
	 *	@param shopName
	 *	@param shopCell
	 *	@param shopDec
	 *	@param shopAddr
	 *	@param shopId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateInfo(String shopName, String shopCell, String shopDec, String shopAddr, String shopId) throws DataAccessException;

	/**
	 *  Update DB table <tt>makeploy_shop_check</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_shop_check set SHOP_ID=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (USER_ID = ?)</tt>
	 *
	 *	@param shopId
	 *	@param userId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateShopId(String shopId, String userId) throws DataAccessException;

}