/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.makeploy.common.dal.dataobject;

import com.onway.makeploy.common.dal.dataobject.BaseDO;

import java.util.Date;

/**
 * A data object class directly models database table <tt>makeploy_commerce</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/makeploy_commerce.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: CommerceDO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class CommerceDO extends BaseDO {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>ID</tt>.
	 */
	private int id;

	/**
	 * This property corresponds to db column <tt>COMMERCE_ID</tt>.
	 */
	private String commerceId;

	/**
	 * This property corresponds to db column <tt>COMMERCE_LEADER</tt>.
	 */
	private String commerceLeader;

	/**
	 * This property corresponds to db column <tt>COMMERCE_VICE_LEADER</tt>.
	 */
	private String commerceViceLeader;

	/**
	 * This property corresponds to db column <tt>COMMERCE_CHARGE</tt>.
	 */
	private String commerceCharge;

	/**
	 * This property corresponds to db column <tt>COMMERCE_SECRETARY_USER</tt>.
	 */
	private String commerceSecretaryUser;

	/**
	 * This property corresponds to db column <tt>COMMERCE_EXECUTIVE_CHAIRMAN</tt>.
	 */
	private String commerceExecutiveChairman;

	/**
	 * This property corresponds to db column <tt>COMMERCE_STANDING_PRESIDENT</tt>.
	 */
	private String commerceStandingPresident;

	/**
	 * This property corresponds to db column <tt>COMMERCE_HONORARY_CHAIRMAN</tt>.
	 */
	private String commerceHonoraryChairman;

	/**
	 * This property corresponds to db column <tt>COMMERCE_EXECUTIVE_DIRECTOR</tt>.
	 */
	private String commerceExecutiveDirector;

	/**
	 * This property corresponds to db column <tt>COMMERCE_MANAGING_DIRECTOR</tt>.
	 */
	private String commerceManagingDirector;

	/**
	 * This property corresponds to db column <tt>COMMERCE_EXECUTIVE</tt>.
	 */
	private String commerceExecutive;

	/**
	 * This property corresponds to db column <tt>COMMERCE_SECRETARY_PARTY</tt>.
	 */
	private String commerceSecretaryParty;

	/**
	 * This property corresponds to db column <tt>COMMERCE_NAME</tt>.
	 */
	private String commerceName;

	/**
	 * This property corresponds to db column <tt>COMMERCE_QRURL</tt>.
	 */
	private String commerceQrurl;

	/**
	 * This property corresponds to db column <tt>COMMERCE_URL</tt>.
	 */
	private String commerceUrl;

	/**
	 * This property corresponds to db column <tt>COMMERCE_CELL</tt>.
	 */
	private String commerceCell;

	/**
	 * This property corresponds to db column <tt>COMMERCE_ADDR</tt>.
	 */
	private String commerceAddr;

	/**
	 * This property corresponds to db column <tt>COMMERCE_DESC</tt>.
	 */
	private String commerceDesc;

	/**
	 * This property corresponds to db column <tt>PEOPLE_NUM</tt>.
	 */
	private int peopleNum;

	/**
	 * This property corresponds to db column <tt>MESSAGE</tt>.
	 */
	private String message;

	/**
	 * This property corresponds to db column <tt>LOACTION_X</tt>.
	 */
	private double loactionX;

	/**
	 * This property corresponds to db column <tt>LOACTION_Y</tt>.
	 */
	private double loactionY;

	/**
	 * This property corresponds to db column <tt>DEL_FLG</tt>.
	 */
	private String delFlg;

	/**
	 * This property corresponds to db column <tt>CREATER</tt>.
	 */
	private String creater;

	/**
	 * This property corresponds to db column <tt>GMT_CREATE</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>MODIFIER</tt>.
	 */
	private String modifier;

	/**
	 * This property corresponds to db column <tt>GMT_MODIFIED</tt>.
	 */
	private Date gmtModified;

	/**
	 * This property corresponds to db column <tt>MEMO</tt>.
	 */
	private String memo;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public int getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(int id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>commerceId</tt>.
     *
     * @return property value of commerceId
     */
	public String getCommerceId() {
		return commerceId;
	}
	
	/**
	 * Setter method for property <tt>commerceId</tt>.
	 * 
	 * @param commerceId value to be assigned to property commerceId
     */
	public void setCommerceId(String commerceId) {
		this.commerceId = commerceId;
	}

    /**
     * Getter method for property <tt>commerceLeader</tt>.
     *
     * @return property value of commerceLeader
     */
	public String getCommerceLeader() {
		return commerceLeader;
	}
	
	/**
	 * Setter method for property <tt>commerceLeader</tt>.
	 * 
	 * @param commerceLeader value to be assigned to property commerceLeader
     */
	public void setCommerceLeader(String commerceLeader) {
		this.commerceLeader = commerceLeader;
	}

    /**
     * Getter method for property <tt>commerceViceLeader</tt>.
     *
     * @return property value of commerceViceLeader
     */
	public String getCommerceViceLeader() {
		return commerceViceLeader;
	}
	
	/**
	 * Setter method for property <tt>commerceViceLeader</tt>.
	 * 
	 * @param commerceViceLeader value to be assigned to property commerceViceLeader
     */
	public void setCommerceViceLeader(String commerceViceLeader) {
		this.commerceViceLeader = commerceViceLeader;
	}

    /**
     * Getter method for property <tt>commerceCharge</tt>.
     *
     * @return property value of commerceCharge
     */
	public String getCommerceCharge() {
		return commerceCharge;
	}
	
	/**
	 * Setter method for property <tt>commerceCharge</tt>.
	 * 
	 * @param commerceCharge value to be assigned to property commerceCharge
     */
	public void setCommerceCharge(String commerceCharge) {
		this.commerceCharge = commerceCharge;
	}

    /**
     * Getter method for property <tt>commerceSecretaryUser</tt>.
     *
     * @return property value of commerceSecretaryUser
     */
	public String getCommerceSecretaryUser() {
		return commerceSecretaryUser;
	}
	
	/**
	 * Setter method for property <tt>commerceSecretaryUser</tt>.
	 * 
	 * @param commerceSecretaryUser value to be assigned to property commerceSecretaryUser
     */
	public void setCommerceSecretaryUser(String commerceSecretaryUser) {
		this.commerceSecretaryUser = commerceSecretaryUser;
	}

    /**
     * Getter method for property <tt>commerceExecutiveChairman</tt>.
     *
     * @return property value of commerceExecutiveChairman
     */
	public String getCommerceExecutiveChairman() {
		return commerceExecutiveChairman;
	}
	
	/**
	 * Setter method for property <tt>commerceExecutiveChairman</tt>.
	 * 
	 * @param commerceExecutiveChairman value to be assigned to property commerceExecutiveChairman
     */
	public void setCommerceExecutiveChairman(String commerceExecutiveChairman) {
		this.commerceExecutiveChairman = commerceExecutiveChairman;
	}

    /**
     * Getter method for property <tt>commerceStandingPresident</tt>.
     *
     * @return property value of commerceStandingPresident
     */
	public String getCommerceStandingPresident() {
		return commerceStandingPresident;
	}
	
	/**
	 * Setter method for property <tt>commerceStandingPresident</tt>.
	 * 
	 * @param commerceStandingPresident value to be assigned to property commerceStandingPresident
     */
	public void setCommerceStandingPresident(String commerceStandingPresident) {
		this.commerceStandingPresident = commerceStandingPresident;
	}

    /**
     * Getter method for property <tt>commerceHonoraryChairman</tt>.
     *
     * @return property value of commerceHonoraryChairman
     */
	public String getCommerceHonoraryChairman() {
		return commerceHonoraryChairman;
	}
	
	/**
	 * Setter method for property <tt>commerceHonoraryChairman</tt>.
	 * 
	 * @param commerceHonoraryChairman value to be assigned to property commerceHonoraryChairman
     */
	public void setCommerceHonoraryChairman(String commerceHonoraryChairman) {
		this.commerceHonoraryChairman = commerceHonoraryChairman;
	}

    /**
     * Getter method for property <tt>commerceExecutiveDirector</tt>.
     *
     * @return property value of commerceExecutiveDirector
     */
	public String getCommerceExecutiveDirector() {
		return commerceExecutiveDirector;
	}
	
	/**
	 * Setter method for property <tt>commerceExecutiveDirector</tt>.
	 * 
	 * @param commerceExecutiveDirector value to be assigned to property commerceExecutiveDirector
     */
	public void setCommerceExecutiveDirector(String commerceExecutiveDirector) {
		this.commerceExecutiveDirector = commerceExecutiveDirector;
	}

    /**
     * Getter method for property <tt>commerceManagingDirector</tt>.
     *
     * @return property value of commerceManagingDirector
     */
	public String getCommerceManagingDirector() {
		return commerceManagingDirector;
	}
	
	/**
	 * Setter method for property <tt>commerceManagingDirector</tt>.
	 * 
	 * @param commerceManagingDirector value to be assigned to property commerceManagingDirector
     */
	public void setCommerceManagingDirector(String commerceManagingDirector) {
		this.commerceManagingDirector = commerceManagingDirector;
	}

    /**
     * Getter method for property <tt>commerceExecutive</tt>.
     *
     * @return property value of commerceExecutive
     */
	public String getCommerceExecutive() {
		return commerceExecutive;
	}
	
	/**
	 * Setter method for property <tt>commerceExecutive</tt>.
	 * 
	 * @param commerceExecutive value to be assigned to property commerceExecutive
     */
	public void setCommerceExecutive(String commerceExecutive) {
		this.commerceExecutive = commerceExecutive;
	}

    /**
     * Getter method for property <tt>commerceSecretaryParty</tt>.
     *
     * @return property value of commerceSecretaryParty
     */
	public String getCommerceSecretaryParty() {
		return commerceSecretaryParty;
	}
	
	/**
	 * Setter method for property <tt>commerceSecretaryParty</tt>.
	 * 
	 * @param commerceSecretaryParty value to be assigned to property commerceSecretaryParty
     */
	public void setCommerceSecretaryParty(String commerceSecretaryParty) {
		this.commerceSecretaryParty = commerceSecretaryParty;
	}

    /**
     * Getter method for property <tt>commerceName</tt>.
     *
     * @return property value of commerceName
     */
	public String getCommerceName() {
		return commerceName;
	}
	
	/**
	 * Setter method for property <tt>commerceName</tt>.
	 * 
	 * @param commerceName value to be assigned to property commerceName
     */
	public void setCommerceName(String commerceName) {
		this.commerceName = commerceName;
	}

    /**
     * Getter method for property <tt>commerceQrurl</tt>.
     *
     * @return property value of commerceQrurl
     */
	public String getCommerceQrurl() {
		return commerceQrurl;
	}
	
	/**
	 * Setter method for property <tt>commerceQrurl</tt>.
	 * 
	 * @param commerceQrurl value to be assigned to property commerceQrurl
     */
	public void setCommerceQrurl(String commerceQrurl) {
		this.commerceQrurl = commerceQrurl;
	}

    /**
     * Getter method for property <tt>commerceUrl</tt>.
     *
     * @return property value of commerceUrl
     */
	public String getCommerceUrl() {
		return commerceUrl;
	}
	
	/**
	 * Setter method for property <tt>commerceUrl</tt>.
	 * 
	 * @param commerceUrl value to be assigned to property commerceUrl
     */
	public void setCommerceUrl(String commerceUrl) {
		this.commerceUrl = commerceUrl;
	}

    /**
     * Getter method for property <tt>commerceCell</tt>.
     *
     * @return property value of commerceCell
     */
	public String getCommerceCell() {
		return commerceCell;
	}
	
	/**
	 * Setter method for property <tt>commerceCell</tt>.
	 * 
	 * @param commerceCell value to be assigned to property commerceCell
     */
	public void setCommerceCell(String commerceCell) {
		this.commerceCell = commerceCell;
	}

    /**
     * Getter method for property <tt>commerceAddr</tt>.
     *
     * @return property value of commerceAddr
     */
	public String getCommerceAddr() {
		return commerceAddr;
	}
	
	/**
	 * Setter method for property <tt>commerceAddr</tt>.
	 * 
	 * @param commerceAddr value to be assigned to property commerceAddr
     */
	public void setCommerceAddr(String commerceAddr) {
		this.commerceAddr = commerceAddr;
	}

    /**
     * Getter method for property <tt>commerceDesc</tt>.
     *
     * @return property value of commerceDesc
     */
	public String getCommerceDesc() {
		return commerceDesc;
	}
	
	/**
	 * Setter method for property <tt>commerceDesc</tt>.
	 * 
	 * @param commerceDesc value to be assigned to property commerceDesc
     */
	public void setCommerceDesc(String commerceDesc) {
		this.commerceDesc = commerceDesc;
	}

    /**
     * Getter method for property <tt>peopleNum</tt>.
     *
     * @return property value of peopleNum
     */
	public int getPeopleNum() {
		return peopleNum;
	}
	
	/**
	 * Setter method for property <tt>peopleNum</tt>.
	 * 
	 * @param peopleNum value to be assigned to property peopleNum
     */
	public void setPeopleNum(int peopleNum) {
		this.peopleNum = peopleNum;
	}

    /**
     * Getter method for property <tt>message</tt>.
     *
     * @return property value of message
     */
	public String getMessage() {
		return message;
	}
	
	/**
	 * Setter method for property <tt>message</tt>.
	 * 
	 * @param message value to be assigned to property message
     */
	public void setMessage(String message) {
		this.message = message;
	}

    /**
     * Getter method for property <tt>loactionX</tt>.
     *
     * @return property value of loactionX
     */
	public double getLoactionX() {
		return loactionX;
	}
	
	/**
	 * Setter method for property <tt>loactionX</tt>.
	 * 
	 * @param loactionX value to be assigned to property loactionX
     */
	public void setLoactionX(double loactionX) {
		this.loactionX = loactionX;
	}

    /**
     * Getter method for property <tt>loactionY</tt>.
     *
     * @return property value of loactionY
     */
	public double getLoactionY() {
		return loactionY;
	}
	
	/**
	 * Setter method for property <tt>loactionY</tt>.
	 * 
	 * @param loactionY value to be assigned to property loactionY
     */
	public void setLoactionY(double loactionY) {
		this.loactionY = loactionY;
	}

    /**
     * Getter method for property <tt>delFlg</tt>.
     *
     * @return property value of delFlg
     */
	public String getDelFlg() {
		return delFlg;
	}
	
	/**
	 * Setter method for property <tt>delFlg</tt>.
	 * 
	 * @param delFlg value to be assigned to property delFlg
     */
	public void setDelFlg(String delFlg) {
		this.delFlg = delFlg;
	}

    /**
     * Getter method for property <tt>creater</tt>.
     *
     * @return property value of creater
     */
	public String getCreater() {
		return creater;
	}
	
	/**
	 * Setter method for property <tt>creater</tt>.
	 * 
	 * @param creater value to be assigned to property creater
     */
	public void setCreater(String creater) {
		this.creater = creater;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>modifier</tt>.
     *
     * @return property value of modifier
     */
	public String getModifier() {
		return modifier;
	}
	
	/**
	 * Setter method for property <tt>modifier</tt>.
	 * 
	 * @param modifier value to be assigned to property modifier
     */
	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

    /**
     * Getter method for property <tt>memo</tt>.
     *
     * @return property value of memo
     */
	public String getMemo() {
		return memo;
	}
	
	/**
	 * Setter method for property <tt>memo</tt>.
	 * 
	 * @param memo value to be assigned to property memo
     */
	public void setMemo(String memo) {
		this.memo = memo;
	}
}
