/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.makeploy.common.dal.dataobject;

import com.onway.makeploy.common.dal.dataobject.BaseDO;

import java.util.Date;

/**
 * A data object class directly models database table <tt>makeploy_inclpostageproviso</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/makeploy_inclpostageproviso.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: InclpostageprovisoDO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class InclpostageprovisoDO extends BaseDO {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>ID</tt>.
	 */
	private int id;

	/**
	 * This property corresponds to db column <tt>TEMPLATE_ID</tt>.
	 */
	private String templateId;

	/**
	 * This property corresponds to db column <tt>FREE_POST_ADDR</tt>.
	 */
	private String freePostAddr;

	/**
	 * This property corresponds to db column <tt>FREE_POST_COUNT</tt>.
	 */
	private int freePostCount;

	/**
	 * This property corresponds to db column <tt>FREE_POST_WEIGHT</tt>.
	 */
	private long freePostWeight;

	/**
	 * This property corresponds to db column <tt>FREE_POST_SIZE</tt>.
	 */
	private long freePostSize;

	/**
	 * This property corresponds to db column <tt>FREE_POST_MONEY</tt>.
	 */
	private long freePostMoney;

	/**
	 * This property corresponds to db column <tt>CREATER</tt>.
	 */
	private String creater;

	/**
	 * This property corresponds to db column <tt>GMT_CREATE</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>MODIFIER</tt>.
	 */
	private String modifier;

	/**
	 * This property corresponds to db column <tt>GMT_MODIFIED</tt>.
	 */
	private Date gmtModified;

	/**
	 * This property corresponds to db column <tt>MEMO</tt>.
	 */
	private String memo;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public int getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(int id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>templateId</tt>.
     *
     * @return property value of templateId
     */
	public String getTemplateId() {
		return templateId;
	}
	
	/**
	 * Setter method for property <tt>templateId</tt>.
	 * 
	 * @param templateId value to be assigned to property templateId
     */
	public void setTemplateId(String templateId) {
		this.templateId = templateId;
	}

    /**
     * Getter method for property <tt>freePostAddr</tt>.
     *
     * @return property value of freePostAddr
     */
	public String getFreePostAddr() {
		return freePostAddr;
	}
	
	/**
	 * Setter method for property <tt>freePostAddr</tt>.
	 * 
	 * @param freePostAddr value to be assigned to property freePostAddr
     */
	public void setFreePostAddr(String freePostAddr) {
		this.freePostAddr = freePostAddr;
	}

    /**
     * Getter method for property <tt>freePostCount</tt>.
     *
     * @return property value of freePostCount
     */
	public int getFreePostCount() {
		return freePostCount;
	}
	
	/**
	 * Setter method for property <tt>freePostCount</tt>.
	 * 
	 * @param freePostCount value to be assigned to property freePostCount
     */
	public void setFreePostCount(int freePostCount) {
		this.freePostCount = freePostCount;
	}

    /**
     * Getter method for property <tt>freePostWeight</tt>.
     *
     * @return property value of freePostWeight
     */
	public long getFreePostWeight() {
		return freePostWeight;
	}
	
	/**
	 * Setter method for property <tt>freePostWeight</tt>.
	 * 
	 * @param freePostWeight value to be assigned to property freePostWeight
     */
	public void setFreePostWeight(long freePostWeight) {
		this.freePostWeight = freePostWeight;
	}

    /**
     * Getter method for property <tt>freePostSize</tt>.
     *
     * @return property value of freePostSize
     */
	public long getFreePostSize() {
		return freePostSize;
	}
	
	/**
	 * Setter method for property <tt>freePostSize</tt>.
	 * 
	 * @param freePostSize value to be assigned to property freePostSize
     */
	public void setFreePostSize(long freePostSize) {
		this.freePostSize = freePostSize;
	}

    /**
     * Getter method for property <tt>freePostMoney</tt>.
     *
     * @return property value of freePostMoney
     */
	public long getFreePostMoney() {
		return freePostMoney;
	}
	
	/**
	 * Setter method for property <tt>freePostMoney</tt>.
	 * 
	 * @param freePostMoney value to be assigned to property freePostMoney
     */
	public void setFreePostMoney(long freePostMoney) {
		this.freePostMoney = freePostMoney;
	}

    /**
     * Getter method for property <tt>creater</tt>.
     *
     * @return property value of creater
     */
	public String getCreater() {
		return creater;
	}
	
	/**
	 * Setter method for property <tt>creater</tt>.
	 * 
	 * @param creater value to be assigned to property creater
     */
	public void setCreater(String creater) {
		this.creater = creater;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>modifier</tt>.
     *
     * @return property value of modifier
     */
	public String getModifier() {
		return modifier;
	}
	
	/**
	 * Setter method for property <tt>modifier</tt>.
	 * 
	 * @param modifier value to be assigned to property modifier
     */
	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

    /**
     * Getter method for property <tt>memo</tt>.
     *
     * @return property value of memo
     */
	public String getMemo() {
		return memo;
	}
	
	/**
	 * Setter method for property <tt>memo</tt>.
	 * 
	 * @param memo value to be assigned to property memo
     */
	public void setMemo(String memo) {
		this.memo = memo;
	}
}
