/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.makeploy.common.dal.dataobject;

import com.onway.makeploy.common.dal.dataobject.BaseDO;

import java.util.Date;
import com.onway.common.lang.Money;

/**
 * A data object class directly models database table <tt>makeploy_order</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/makeploy_order.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: OrderDO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class OrderDO extends BaseDO {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>ID</tt>.
	 */
	private int id;

	/**
	 * This property corresponds to db column <tt>USER_ID</tt>.
	 */
	private String userId;

	/**
	 * This property corresponds to db column <tt>USER_NAME</tt>.
	 */
	private String userName;

	/**
	 * This property corresponds to db column <tt>ADDRESS_NO</tt>.
	 */
	private String addressNo;

	/**
	 * This property corresponds to db column <tt>ORDER_NO</tt>.
	 */
	private String orderNo;

	/**
	 * This property corresponds to db column <tt>ORDER_ID</tt>.
	 */
	private String orderId;

	/**
	 * This property corresponds to db column <tt>ORDER_NUM</tt>.
	 */
	private int orderNum;

	/**
	 * This property corresponds to db column <tt>CELL</tt>.
	 */
	private String cell;

	/**
	 * This property corresponds to db column <tt>PAY_NO</tt>.
	 */
	private String payNo;

	/**
	 * This property corresponds to db column <tt>PARFLAG</tt>.
	 */
	private String parflag;

	/**
	 * This property corresponds to db column <tt>TRANSPORT_NO</tt>.
	 */
	private String transportNo;

	/**
	 * This property corresponds to db column <tt>PRODUCT_NO</tt>.
	 */
	private String productNo;

	/**
	 * This property corresponds to db column <tt>EACHPRO_COUNT</tt>.
	 */
	private String eachproCount;

	/**
	 * This property corresponds to db column <tt>PRODUCT_COUNT</tt>.
	 */
	private int productCount;

	/**
	 * This property corresponds to db column <tt>EACHPRO_PRICE</tt>.
	 */
	private Money eachproPrice = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>POINT</tt>.
	 */
	private Money point = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>SHOP_ID</tt>.
	 */
	private String shopId;

	/**
	 * This property corresponds to db column <tt>ORDER_PRICE</tt>.
	 */
	private Money orderPrice = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>PAY_STATUS</tt>.
	 */
	private String payStatus;

	/**
	 * This property corresponds to db column <tt>SEND_GOODS</tt>.
	 */
	private String sendGoods;

	/**
	 * This property corresponds to db column <tt>PAY_TIME</tt>.
	 */
	private Date payTime;

	/**
	 * This property corresponds to db column <tt>PAY_WAY</tt>.
	 */
	private String payWay;

	/**
	 * This property corresponds to db column <tt>ORDER_TYPE</tt>.
	 */
	private String orderType;

	/**
	 * This property corresponds to db column <tt>ORDER_STATUS</tt>.
	 */
	private String orderStatus;

	/**
	 * This property corresponds to db column <tt>LUGGAGE</tt>.
	 */
	private Money luggage = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>DELFLAG</tt>.
	 */
	private String delflag;

	/**
	 * This property corresponds to db column <tt>EXPECTED_RETURN</tt>.
	 */
	private Money expectedReturn = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>EXPECTED_INTEGRAL</tt>.
	 */
	private long expectedIntegral;

	/**
	 * This property corresponds to db column <tt>ACTUAL_RETURN</tt>.
	 */
	private Money actualReturn = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>ACTUAL_INTEGRAL</tt>.
	 */
	private long actualIntegral;

	/**
	 * This property corresponds to db column <tt>RETURN_FLG</tt>.
	 */
	private String returnFlg;

	/**
	 * This property corresponds to db column <tt>PROVIENCE</tt>.
	 */
	private String provience;

	/**
	 * This property corresponds to db column <tt>CITY</tt>.
	 */
	private String city;

	/**
	 * This property corresponds to db column <tt>DISTRICT</tt>.
	 */
	private String district;

	/**
	 * This property corresponds to db column <tt>ADDR</tt>.
	 */
	private String addr;

	/**
	 * This property corresponds to db column <tt>CREATER</tt>.
	 */
	private String creater;

	/**
	 * This property corresponds to db column <tt>GMT_CREATE</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>MODIFIER</tt>.
	 */
	private String modifier;

	/**
	 * This property corresponds to db column <tt>GMT_MODIFIED</tt>.
	 */
	private Date gmtModified;

	/**
	 * This property corresponds to db column <tt>MEMO</tt>.
	 */
	private String memo;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public int getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(int id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>userId</tt>.
     *
     * @return property value of userId
     */
	public String getUserId() {
		return userId;
	}
	
	/**
	 * Setter method for property <tt>userId</tt>.
	 * 
	 * @param userId value to be assigned to property userId
     */
	public void setUserId(String userId) {
		this.userId = userId;
	}

    /**
     * Getter method for property <tt>userName</tt>.
     *
     * @return property value of userName
     */
	public String getUserName() {
		return userName;
	}
	
	/**
	 * Setter method for property <tt>userName</tt>.
	 * 
	 * @param userName value to be assigned to property userName
     */
	public void setUserName(String userName) {
		this.userName = userName;
	}

    /**
     * Getter method for property <tt>addressNo</tt>.
     *
     * @return property value of addressNo
     */
	public String getAddressNo() {
		return addressNo;
	}
	
	/**
	 * Setter method for property <tt>addressNo</tt>.
	 * 
	 * @param addressNo value to be assigned to property addressNo
     */
	public void setAddressNo(String addressNo) {
		this.addressNo = addressNo;
	}

    /**
     * Getter method for property <tt>orderNo</tt>.
     *
     * @return property value of orderNo
     */
	public String getOrderNo() {
		return orderNo;
	}
	
	/**
	 * Setter method for property <tt>orderNo</tt>.
	 * 
	 * @param orderNo value to be assigned to property orderNo
     */
	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

    /**
     * Getter method for property <tt>orderId</tt>.
     *
     * @return property value of orderId
     */
	public String getOrderId() {
		return orderId;
	}
	
	/**
	 * Setter method for property <tt>orderId</tt>.
	 * 
	 * @param orderId value to be assigned to property orderId
     */
	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

    /**
     * Getter method for property <tt>orderNum</tt>.
     *
     * @return property value of orderNum
     */
	public int getOrderNum() {
		return orderNum;
	}
	
	/**
	 * Setter method for property <tt>orderNum</tt>.
	 * 
	 * @param orderNum value to be assigned to property orderNum
     */
	public void setOrderNum(int orderNum) {
		this.orderNum = orderNum;
	}

    /**
     * Getter method for property <tt>cell</tt>.
     *
     * @return property value of cell
     */
	public String getCell() {
		return cell;
	}
	
	/**
	 * Setter method for property <tt>cell</tt>.
	 * 
	 * @param cell value to be assigned to property cell
     */
	public void setCell(String cell) {
		this.cell = cell;
	}

    /**
     * Getter method for property <tt>payNo</tt>.
     *
     * @return property value of payNo
     */
	public String getPayNo() {
		return payNo;
	}
	
	/**
	 * Setter method for property <tt>payNo</tt>.
	 * 
	 * @param payNo value to be assigned to property payNo
     */
	public void setPayNo(String payNo) {
		this.payNo = payNo;
	}

    /**
     * Getter method for property <tt>parflag</tt>.
     *
     * @return property value of parflag
     */
	public String getParflag() {
		return parflag;
	}
	
	/**
	 * Setter method for property <tt>parflag</tt>.
	 * 
	 * @param parflag value to be assigned to property parflag
     */
	public void setParflag(String parflag) {
		this.parflag = parflag;
	}

    /**
     * Getter method for property <tt>transportNo</tt>.
     *
     * @return property value of transportNo
     */
	public String getTransportNo() {
		return transportNo;
	}
	
	/**
	 * Setter method for property <tt>transportNo</tt>.
	 * 
	 * @param transportNo value to be assigned to property transportNo
     */
	public void setTransportNo(String transportNo) {
		this.transportNo = transportNo;
	}

    /**
     * Getter method for property <tt>productNo</tt>.
     *
     * @return property value of productNo
     */
	public String getProductNo() {
		return productNo;
	}
	
	/**
	 * Setter method for property <tt>productNo</tt>.
	 * 
	 * @param productNo value to be assigned to property productNo
     */
	public void setProductNo(String productNo) {
		this.productNo = productNo;
	}

    /**
     * Getter method for property <tt>eachproCount</tt>.
     *
     * @return property value of eachproCount
     */
	public String getEachproCount() {
		return eachproCount;
	}
	
	/**
	 * Setter method for property <tt>eachproCount</tt>.
	 * 
	 * @param eachproCount value to be assigned to property eachproCount
     */
	public void setEachproCount(String eachproCount) {
		this.eachproCount = eachproCount;
	}

    /**
     * Getter method for property <tt>productCount</tt>.
     *
     * @return property value of productCount
     */
	public int getProductCount() {
		return productCount;
	}
	
	/**
	 * Setter method for property <tt>productCount</tt>.
	 * 
	 * @param productCount value to be assigned to property productCount
     */
	public void setProductCount(int productCount) {
		this.productCount = productCount;
	}

    /**
     * Getter method for property <tt>eachproPrice</tt>.
     *
     * @return property value of eachproPrice
     */
	public Money getEachproPrice() {
		return eachproPrice;
	}
	
	/**
	 * Setter method for property <tt>eachproPrice</tt>.
	 * 
	 * @param eachproPrice value to be assigned to property eachproPrice
     */
	public void setEachproPrice(Money eachproPrice) {
		if (eachproPrice == null) {
			this.eachproPrice = new Money(0, 0);
		} else {
			this.eachproPrice = eachproPrice;
		}
	}

    /**
     * Getter method for property <tt>point</tt>.
     *
     * @return property value of point
     */
	public Money getPoint() {
		return point;
	}
	
	/**
	 * Setter method for property <tt>point</tt>.
	 * 
	 * @param point value to be assigned to property point
     */
	public void setPoint(Money point) {
		if (point == null) {
			this.point = new Money(0, 0);
		} else {
			this.point = point;
		}
	}

    /**
     * Getter method for property <tt>shopId</tt>.
     *
     * @return property value of shopId
     */
	public String getShopId() {
		return shopId;
	}
	
	/**
	 * Setter method for property <tt>shopId</tt>.
	 * 
	 * @param shopId value to be assigned to property shopId
     */
	public void setShopId(String shopId) {
		this.shopId = shopId;
	}

    /**
     * Getter method for property <tt>orderPrice</tt>.
     *
     * @return property value of orderPrice
     */
	public Money getOrderPrice() {
		return orderPrice;
	}
	
	/**
	 * Setter method for property <tt>orderPrice</tt>.
	 * 
	 * @param orderPrice value to be assigned to property orderPrice
     */
	public void setOrderPrice(Money orderPrice) {
		if (orderPrice == null) {
			this.orderPrice = new Money(0, 0);
		} else {
			this.orderPrice = orderPrice;
		}
	}

    /**
     * Getter method for property <tt>payStatus</tt>.
     *
     * @return property value of payStatus
     */
	public String getPayStatus() {
		return payStatus;
	}
	
	/**
	 * Setter method for property <tt>payStatus</tt>.
	 * 
	 * @param payStatus value to be assigned to property payStatus
     */
	public void setPayStatus(String payStatus) {
		this.payStatus = payStatus;
	}

    /**
     * Getter method for property <tt>sendGoods</tt>.
     *
     * @return property value of sendGoods
     */
	public String getSendGoods() {
		return sendGoods;
	}
	
	/**
	 * Setter method for property <tt>sendGoods</tt>.
	 * 
	 * @param sendGoods value to be assigned to property sendGoods
     */
	public void setSendGoods(String sendGoods) {
		this.sendGoods = sendGoods;
	}

    /**
     * Getter method for property <tt>payTime</tt>.
     *
     * @return property value of payTime
     */
	public Date getPayTime() {
		return payTime;
	}
	
	/**
	 * Setter method for property <tt>payTime</tt>.
	 * 
	 * @param payTime value to be assigned to property payTime
     */
	public void setPayTime(Date payTime) {
		this.payTime = payTime;
	}

    /**
     * Getter method for property <tt>payWay</tt>.
     *
     * @return property value of payWay
     */
	public String getPayWay() {
		return payWay;
	}
	
	/**
	 * Setter method for property <tt>payWay</tt>.
	 * 
	 * @param payWay value to be assigned to property payWay
     */
	public void setPayWay(String payWay) {
		this.payWay = payWay;
	}

    /**
     * Getter method for property <tt>orderType</tt>.
     *
     * @return property value of orderType
     */
	public String getOrderType() {
		return orderType;
	}
	
	/**
	 * Setter method for property <tt>orderType</tt>.
	 * 
	 * @param orderType value to be assigned to property orderType
     */
	public void setOrderType(String orderType) {
		this.orderType = orderType;
	}

    /**
     * Getter method for property <tt>orderStatus</tt>.
     *
     * @return property value of orderStatus
     */
	public String getOrderStatus() {
		return orderStatus;
	}
	
	/**
	 * Setter method for property <tt>orderStatus</tt>.
	 * 
	 * @param orderStatus value to be assigned to property orderStatus
     */
	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}

    /**
     * Getter method for property <tt>luggage</tt>.
     *
     * @return property value of luggage
     */
	public Money getLuggage() {
		return luggage;
	}
	
	/**
	 * Setter method for property <tt>luggage</tt>.
	 * 
	 * @param luggage value to be assigned to property luggage
     */
	public void setLuggage(Money luggage) {
		if (luggage == null) {
			this.luggage = new Money(0, 0);
		} else {
			this.luggage = luggage;
		}
	}

    /**
     * Getter method for property <tt>delflag</tt>.
     *
     * @return property value of delflag
     */
	public String getDelflag() {
		return delflag;
	}
	
	/**
	 * Setter method for property <tt>delflag</tt>.
	 * 
	 * @param delflag value to be assigned to property delflag
     */
	public void setDelflag(String delflag) {
		this.delflag = delflag;
	}

    /**
     * Getter method for property <tt>expectedReturn</tt>.
     *
     * @return property value of expectedReturn
     */
	public Money getExpectedReturn() {
		return expectedReturn;
	}
	
	/**
	 * Setter method for property <tt>expectedReturn</tt>.
	 * 
	 * @param expectedReturn value to be assigned to property expectedReturn
     */
	public void setExpectedReturn(Money expectedReturn) {
		if (expectedReturn == null) {
			this.expectedReturn = new Money(0, 0);
		} else {
			this.expectedReturn = expectedReturn;
		}
	}

    /**
     * Getter method for property <tt>expectedIntegral</tt>.
     *
     * @return property value of expectedIntegral
     */
	public long getExpectedIntegral() {
		return expectedIntegral;
	}
	
	/**
	 * Setter method for property <tt>expectedIntegral</tt>.
	 * 
	 * @param expectedIntegral value to be assigned to property expectedIntegral
     */
	public void setExpectedIntegral(long expectedIntegral) {
		this.expectedIntegral = expectedIntegral;
	}

    /**
     * Getter method for property <tt>actualReturn</tt>.
     *
     * @return property value of actualReturn
     */
	public Money getActualReturn() {
		return actualReturn;
	}
	
	/**
	 * Setter method for property <tt>actualReturn</tt>.
	 * 
	 * @param actualReturn value to be assigned to property actualReturn
     */
	public void setActualReturn(Money actualReturn) {
		if (actualReturn == null) {
			this.actualReturn = new Money(0, 0);
		} else {
			this.actualReturn = actualReturn;
		}
	}

    /**
     * Getter method for property <tt>actualIntegral</tt>.
     *
     * @return property value of actualIntegral
     */
	public long getActualIntegral() {
		return actualIntegral;
	}
	
	/**
	 * Setter method for property <tt>actualIntegral</tt>.
	 * 
	 * @param actualIntegral value to be assigned to property actualIntegral
     */
	public void setActualIntegral(long actualIntegral) {
		this.actualIntegral = actualIntegral;
	}

    /**
     * Getter method for property <tt>returnFlg</tt>.
     *
     * @return property value of returnFlg
     */
	public String getReturnFlg() {
		return returnFlg;
	}
	
	/**
	 * Setter method for property <tt>returnFlg</tt>.
	 * 
	 * @param returnFlg value to be assigned to property returnFlg
     */
	public void setReturnFlg(String returnFlg) {
		this.returnFlg = returnFlg;
	}

    /**
     * Getter method for property <tt>provience</tt>.
     *
     * @return property value of provience
     */
	public String getProvience() {
		return provience;
	}
	
	/**
	 * Setter method for property <tt>provience</tt>.
	 * 
	 * @param provience value to be assigned to property provience
     */
	public void setProvience(String provience) {
		this.provience = provience;
	}

    /**
     * Getter method for property <tt>city</tt>.
     *
     * @return property value of city
     */
	public String getCity() {
		return city;
	}
	
	/**
	 * Setter method for property <tt>city</tt>.
	 * 
	 * @param city value to be assigned to property city
     */
	public void setCity(String city) {
		this.city = city;
	}

    /**
     * Getter method for property <tt>district</tt>.
     *
     * @return property value of district
     */
	public String getDistrict() {
		return district;
	}
	
	/**
	 * Setter method for property <tt>district</tt>.
	 * 
	 * @param district value to be assigned to property district
     */
	public void setDistrict(String district) {
		this.district = district;
	}

    /**
     * Getter method for property <tt>addr</tt>.
     *
     * @return property value of addr
     */
	public String getAddr() {
		return addr;
	}
	
	/**
	 * Setter method for property <tt>addr</tt>.
	 * 
	 * @param addr value to be assigned to property addr
     */
	public void setAddr(String addr) {
		this.addr = addr;
	}

    /**
     * Getter method for property <tt>creater</tt>.
     *
     * @return property value of creater
     */
	public String getCreater() {
		return creater;
	}
	
	/**
	 * Setter method for property <tt>creater</tt>.
	 * 
	 * @param creater value to be assigned to property creater
     */
	public void setCreater(String creater) {
		this.creater = creater;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>modifier</tt>.
     *
     * @return property value of modifier
     */
	public String getModifier() {
		return modifier;
	}
	
	/**
	 * Setter method for property <tt>modifier</tt>.
	 * 
	 * @param modifier value to be assigned to property modifier
     */
	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

    /**
     * Getter method for property <tt>memo</tt>.
     *
     * @return property value of memo
     */
	public String getMemo() {
		return memo;
	}
	
	/**
	 * Setter method for property <tt>memo</tt>.
	 * 
	 * @param memo value to be assigned to property memo
     */
	public void setMemo(String memo) {
		this.memo = memo;
	}
}
