/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.makeploy.common.dal.dataobject;

import com.onway.makeploy.common.dal.dataobject.BaseDO;

import com.onway.common.lang.Money;
import java.util.Date;

/**
 * A data object class directly models database table <tt>makeploy_product_promotion</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/makeploy_product_promotion.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: ProductPromotionDO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class ProductPromotionDO extends BaseDO {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>ID</tt>.
	 */
	private int id;

	/**
	 * This property corresponds to db column <tt>USER_ID</tt>.
	 */
	private String userId;

	/**
	 * This property corresponds to db column <tt>USER_NAME</tt>.
	 */
	private String userName;

	/**
	 * This property corresponds to db column <tt>CELL</tt>.
	 */
	private String cell;

	/**
	 * This property corresponds to db column <tt>SHOP_ID</tt>.
	 */
	private String shopId;

	/**
	 * This property corresponds to db column <tt>SHOP_NAME</tt>.
	 */
	private String shopName;

	/**
	 * This property corresponds to db column <tt>PRODUCT_NO</tt>.
	 */
	private String productNo;

	/**
	 * This property corresponds to db column <tt>PRODUCT_NAME</tt>.
	 */
	private String productName;

	/**
	 * This property corresponds to db column <tt>INDUSTRY</tt>.
	 */
	private String industry;

	/**
	 * This property corresponds to db column <tt>STATUS</tt>.
	 */
	private String status;

	/**
	 * This property corresponds to db column <tt>TYPE</tt>.
	 */
	private String type;

	/**
	 * This property corresponds to db column <tt>NEED_PEOPLE</tt>.
	 */
	private int needPeople;

	/**
	 * This property corresponds to db column <tt>PRICE</tt>.
	 */
	private Money price = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>OLD_PRICE</tt>.
	 */
	private Money oldPrice = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>SOLE_COUNT</tt>.
	 */
	private int soleCount;

	/**
	 * This property corresponds to db column <tt>POST_WAY</tt>.
	 */
	private String postWay;

	/**
	 * This property corresponds to db column <tt>MESSAGES</tt>.
	 */
	private String messages;

	/**
	 * This property corresponds to db column <tt>PRODUCT_URL</tt>.
	 */
	private String productUrl;

	/**
	 * This property corresponds to db column <tt>CREATER</tt>.
	 */
	private String creater;

	/**
	 * This property corresponds to db column <tt>GMT_CREATE</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>MODIFIER</tt>.
	 */
	private String modifier;

	/**
	 * This property corresponds to db column <tt>GMT_MODIFIED</tt>.
	 */
	private Date gmtModified;

	/**
	 * This property corresponds to db column <tt>MEMO</tt>.
	 */
	private String memo;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public int getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(int id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>userId</tt>.
     *
     * @return property value of userId
     */
	public String getUserId() {
		return userId;
	}
	
	/**
	 * Setter method for property <tt>userId</tt>.
	 * 
	 * @param userId value to be assigned to property userId
     */
	public void setUserId(String userId) {
		this.userId = userId;
	}

    /**
     * Getter method for property <tt>userName</tt>.
     *
     * @return property value of userName
     */
	public String getUserName() {
		return userName;
	}
	
	/**
	 * Setter method for property <tt>userName</tt>.
	 * 
	 * @param userName value to be assigned to property userName
     */
	public void setUserName(String userName) {
		this.userName = userName;
	}

    /**
     * Getter method for property <tt>cell</tt>.
     *
     * @return property value of cell
     */
	public String getCell() {
		return cell;
	}
	
	/**
	 * Setter method for property <tt>cell</tt>.
	 * 
	 * @param cell value to be assigned to property cell
     */
	public void setCell(String cell) {
		this.cell = cell;
	}

    /**
     * Getter method for property <tt>shopId</tt>.
     *
     * @return property value of shopId
     */
	public String getShopId() {
		return shopId;
	}
	
	/**
	 * Setter method for property <tt>shopId</tt>.
	 * 
	 * @param shopId value to be assigned to property shopId
     */
	public void setShopId(String shopId) {
		this.shopId = shopId;
	}

    /**
     * Getter method for property <tt>shopName</tt>.
     *
     * @return property value of shopName
     */
	public String getShopName() {
		return shopName;
	}
	
	/**
	 * Setter method for property <tt>shopName</tt>.
	 * 
	 * @param shopName value to be assigned to property shopName
     */
	public void setShopName(String shopName) {
		this.shopName = shopName;
	}

    /**
     * Getter method for property <tt>productNo</tt>.
     *
     * @return property value of productNo
     */
	public String getProductNo() {
		return productNo;
	}
	
	/**
	 * Setter method for property <tt>productNo</tt>.
	 * 
	 * @param productNo value to be assigned to property productNo
     */
	public void setProductNo(String productNo) {
		this.productNo = productNo;
	}

    /**
     * Getter method for property <tt>productName</tt>.
     *
     * @return property value of productName
     */
	public String getProductName() {
		return productName;
	}
	
	/**
	 * Setter method for property <tt>productName</tt>.
	 * 
	 * @param productName value to be assigned to property productName
     */
	public void setProductName(String productName) {
		this.productName = productName;
	}

    /**
     * Getter method for property <tt>industry</tt>.
     *
     * @return property value of industry
     */
	public String getIndustry() {
		return industry;
	}
	
	/**
	 * Setter method for property <tt>industry</tt>.
	 * 
	 * @param industry value to be assigned to property industry
     */
	public void setIndustry(String industry) {
		this.industry = industry;
	}

    /**
     * Getter method for property <tt>status</tt>.
     *
     * @return property value of status
     */
	public String getStatus() {
		return status;
	}
	
	/**
	 * Setter method for property <tt>status</tt>.
	 * 
	 * @param status value to be assigned to property status
     */
	public void setStatus(String status) {
		this.status = status;
	}

    /**
     * Getter method for property <tt>type</tt>.
     *
     * @return property value of type
     */
	public String getType() {
		return type;
	}
	
	/**
	 * Setter method for property <tt>type</tt>.
	 * 
	 * @param type value to be assigned to property type
     */
	public void setType(String type) {
		this.type = type;
	}

    /**
     * Getter method for property <tt>needPeople</tt>.
     *
     * @return property value of needPeople
     */
	public int getNeedPeople() {
		return needPeople;
	}
	
	/**
	 * Setter method for property <tt>needPeople</tt>.
	 * 
	 * @param needPeople value to be assigned to property needPeople
     */
	public void setNeedPeople(int needPeople) {
		this.needPeople = needPeople;
	}

    /**
     * Getter method for property <tt>price</tt>.
     *
     * @return property value of price
     */
	public Money getPrice() {
		return price;
	}
	
	/**
	 * Setter method for property <tt>price</tt>.
	 * 
	 * @param price value to be assigned to property price
     */
	public void setPrice(Money price) {
		if (price == null) {
			this.price = new Money(0, 0);
		} else {
			this.price = price;
		}
	}

    /**
     * Getter method for property <tt>oldPrice</tt>.
     *
     * @return property value of oldPrice
     */
	public Money getOldPrice() {
		return oldPrice;
	}
	
	/**
	 * Setter method for property <tt>oldPrice</tt>.
	 * 
	 * @param oldPrice value to be assigned to property oldPrice
     */
	public void setOldPrice(Money oldPrice) {
		if (oldPrice == null) {
			this.oldPrice = new Money(0, 0);
		} else {
			this.oldPrice = oldPrice;
		}
	}

    /**
     * Getter method for property <tt>soleCount</tt>.
     *
     * @return property value of soleCount
     */
	public int getSoleCount() {
		return soleCount;
	}
	
	/**
	 * Setter method for property <tt>soleCount</tt>.
	 * 
	 * @param soleCount value to be assigned to property soleCount
     */
	public void setSoleCount(int soleCount) {
		this.soleCount = soleCount;
	}

    /**
     * Getter method for property <tt>postWay</tt>.
     *
     * @return property value of postWay
     */
	public String getPostWay() {
		return postWay;
	}
	
	/**
	 * Setter method for property <tt>postWay</tt>.
	 * 
	 * @param postWay value to be assigned to property postWay
     */
	public void setPostWay(String postWay) {
		this.postWay = postWay;
	}

    /**
     * Getter method for property <tt>messages</tt>.
     *
     * @return property value of messages
     */
	public String getMessages() {
		return messages;
	}
	
	/**
	 * Setter method for property <tt>messages</tt>.
	 * 
	 * @param messages value to be assigned to property messages
     */
	public void setMessages(String messages) {
		this.messages = messages;
	}

    /**
     * Getter method for property <tt>productUrl</tt>.
     *
     * @return property value of productUrl
     */
	public String getProductUrl() {
		return productUrl;
	}
	
	/**
	 * Setter method for property <tt>productUrl</tt>.
	 * 
	 * @param productUrl value to be assigned to property productUrl
     */
	public void setProductUrl(String productUrl) {
		this.productUrl = productUrl;
	}

    /**
     * Getter method for property <tt>creater</tt>.
     *
     * @return property value of creater
     */
	public String getCreater() {
		return creater;
	}
	
	/**
	 * Setter method for property <tt>creater</tt>.
	 * 
	 * @param creater value to be assigned to property creater
     */
	public void setCreater(String creater) {
		this.creater = creater;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>modifier</tt>.
     *
     * @return property value of modifier
     */
	public String getModifier() {
		return modifier;
	}
	
	/**
	 * Setter method for property <tt>modifier</tt>.
	 * 
	 * @param modifier value to be assigned to property modifier
     */
	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

    /**
     * Getter method for property <tt>memo</tt>.
     *
     * @return property value of memo
     */
	public String getMemo() {
		return memo;
	}
	
	/**
	 * Setter method for property <tt>memo</tt>.
	 * 
	 * @param memo value to be assigned to property memo
     */
	public void setMemo(String memo) {
		this.memo = memo;
	}
}
