/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.makeploy.common.dal.dataobject;

import com.onway.makeploy.common.dal.dataobject.BaseDO;

import com.onway.common.lang.Money;
import java.util.Date;

/**
 * A data object class directly models database table <tt>makeploy_product</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/makeploy_product.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: ProductDO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class ProductDO extends BaseDO {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>ID</tt>.
	 */
	private int id;

	/**
	 * This property corresponds to db column <tt>SHOP_ID</tt>.
	 */
	private String shopId;

	/**
	 * This property corresponds to db column <tt>USER_ID</tt>.
	 */
	private String userId;

	/**
	 * This property corresponds to db column <tt>NEED_PEOPLE</tt>.
	 */
	private int needPeople;

	/**
	 * This property corresponds to db column <tt>NOW_PEOPLE</tt>.
	 */
	private int nowPeople;

	/**
	 * This property corresponds to db column <tt>PRODUCT_NO</tt>.
	 */
	private String productNo;

	/**
	 * This property corresponds to db column <tt>PRODUCT_NAME</tt>.
	 */
	private String productName;

	/**
	 * This property corresponds to db column <tt>TEMPLATE_ID</tt>.
	 */
	private String templateId;

	/**
	 * This property corresponds to db column <tt>PRODUCT_WEIGHT</tt>.
	 */
	private double productWeight;

	/**
	 * This property corresponds to db column <tt>PRODUCT_TYPE</tt>.
	 */
	private String productType;

	/**
	 * This property corresponds to db column <tt>CHILDREN</tt>.
	 */
	private String children;

	/**
	 * This property corresponds to db column <tt>OTHER_TYPE</tt>.
	 */
	private String otherType;

	/**
	 * This property corresponds to db column <tt>PRODUCT_OFF</tt>.
	 */
	private double productOff;

	/**
	 * This property corresponds to db column <tt>PRICE</tt>.
	 */
	private Money price = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>LUGGAGE</tt>.
	 */
	private Money luggage = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>USE_POINT</tt>.
	 */
	private Money usePoint = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>OLD_PRICE</tt>.
	 */
	private Money oldPrice = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>SOLE_COUNT</tt>.
	 */
	private int soleCount;

	/**
	 * This property corresponds to db column <tt>CHECK_STATUS</tt>.
	 */
	private String checkStatus;

	/**
	 * This property corresponds to db column <tt>STATUS</tt>.
	 */
	private String status;

	/**
	 * This property corresponds to db column <tt>STOCK</tt>.
	 */
	private int stock;

	/**
	 * This property corresponds to db column <tt>PRODUCT_URL</tt>.
	 */
	private String productUrl;

	/**
	 * This property corresponds to db column <tt>DEL_FLG</tt>.
	 */
	private String delFlg;

	/**
	 * This property corresponds to db column <tt>RECOMMEND_FLG</tt>.
	 */
	private String recommendFlg;

	/**
	 * This property corresponds to db column <tt>PROPORTION_RETURN</tt>.
	 */
	private double proportionReturn;

	/**
	 * This property corresponds to db column <tt>PROPORTION_INTEGRAL</tt>.
	 */
	private double proportionIntegral;

	/**
	 * This property corresponds to db column <tt>CREATER</tt>.
	 */
	private String creater;

	/**
	 * This property corresponds to db column <tt>GMT_CREATE</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>MODIFIER</tt>.
	 */
	private String modifier;

	/**
	 * This property corresponds to db column <tt>GMT_MODIFIED</tt>.
	 */
	private Date gmtModified;

	/**
	 * This property corresponds to db column <tt>MEMO</tt>.
	 */
	private String memo;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public int getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(int id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>shopId</tt>.
     *
     * @return property value of shopId
     */
	public String getShopId() {
		return shopId;
	}
	
	/**
	 * Setter method for property <tt>shopId</tt>.
	 * 
	 * @param shopId value to be assigned to property shopId
     */
	public void setShopId(String shopId) {
		this.shopId = shopId;
	}

    /**
     * Getter method for property <tt>userId</tt>.
     *
     * @return property value of userId
     */
	public String getUserId() {
		return userId;
	}
	
	/**
	 * Setter method for property <tt>userId</tt>.
	 * 
	 * @param userId value to be assigned to property userId
     */
	public void setUserId(String userId) {
		this.userId = userId;
	}

    /**
     * Getter method for property <tt>needPeople</tt>.
     *
     * @return property value of needPeople
     */
	public int getNeedPeople() {
		return needPeople;
	}
	
	/**
	 * Setter method for property <tt>needPeople</tt>.
	 * 
	 * @param needPeople value to be assigned to property needPeople
     */
	public void setNeedPeople(int needPeople) {
		this.needPeople = needPeople;
	}

    /**
     * Getter method for property <tt>nowPeople</tt>.
     *
     * @return property value of nowPeople
     */
	public int getNowPeople() {
		return nowPeople;
	}
	
	/**
	 * Setter method for property <tt>nowPeople</tt>.
	 * 
	 * @param nowPeople value to be assigned to property nowPeople
     */
	public void setNowPeople(int nowPeople) {
		this.nowPeople = nowPeople;
	}

    /**
     * Getter method for property <tt>productNo</tt>.
     *
     * @return property value of productNo
     */
	public String getProductNo() {
		return productNo;
	}
	
	/**
	 * Setter method for property <tt>productNo</tt>.
	 * 
	 * @param productNo value to be assigned to property productNo
     */
	public void setProductNo(String productNo) {
		this.productNo = productNo;
	}

    /**
     * Getter method for property <tt>productName</tt>.
     *
     * @return property value of productName
     */
	public String getProductName() {
		return productName;
	}
	
	/**
	 * Setter method for property <tt>productName</tt>.
	 * 
	 * @param productName value to be assigned to property productName
     */
	public void setProductName(String productName) {
		this.productName = productName;
	}

    /**
     * Getter method for property <tt>templateId</tt>.
     *
     * @return property value of templateId
     */
	public String getTemplateId() {
		return templateId;
	}
	
	/**
	 * Setter method for property <tt>templateId</tt>.
	 * 
	 * @param templateId value to be assigned to property templateId
     */
	public void setTemplateId(String templateId) {
		this.templateId = templateId;
	}

    /**
     * Getter method for property <tt>productWeight</tt>.
     *
     * @return property value of productWeight
     */
	public double getProductWeight() {
		return productWeight;
	}
	
	/**
	 * Setter method for property <tt>productWeight</tt>.
	 * 
	 * @param productWeight value to be assigned to property productWeight
     */
	public void setProductWeight(double productWeight) {
		this.productWeight = productWeight;
	}

    /**
     * Getter method for property <tt>productType</tt>.
     *
     * @return property value of productType
     */
	public String getProductType() {
		return productType;
	}
	
	/**
	 * Setter method for property <tt>productType</tt>.
	 * 
	 * @param productType value to be assigned to property productType
     */
	public void setProductType(String productType) {
		this.productType = productType;
	}

    /**
     * Getter method for property <tt>children</tt>.
     *
     * @return property value of children
     */
	public String getChildren() {
		return children;
	}
	
	/**
	 * Setter method for property <tt>children</tt>.
	 * 
	 * @param children value to be assigned to property children
     */
	public void setChildren(String children) {
		this.children = children;
	}

    /**
     * Getter method for property <tt>otherType</tt>.
     *
     * @return property value of otherType
     */
	public String getOtherType() {
		return otherType;
	}
	
	/**
	 * Setter method for property <tt>otherType</tt>.
	 * 
	 * @param otherType value to be assigned to property otherType
     */
	public void setOtherType(String otherType) {
		this.otherType = otherType;
	}

    /**
     * Getter method for property <tt>productOff</tt>.
     *
     * @return property value of productOff
     */
	public double getProductOff() {
		return productOff;
	}
	
	/**
	 * Setter method for property <tt>productOff</tt>.
	 * 
	 * @param productOff value to be assigned to property productOff
     */
	public void setProductOff(double productOff) {
		this.productOff = productOff;
	}

    /**
     * Getter method for property <tt>price</tt>.
     *
     * @return property value of price
     */
	public Money getPrice() {
		return price;
	}
	
	/**
	 * Setter method for property <tt>price</tt>.
	 * 
	 * @param price value to be assigned to property price
     */
	public void setPrice(Money price) {
		if (price == null) {
			this.price = new Money(0, 0);
		} else {
			this.price = price;
		}
	}

    /**
     * Getter method for property <tt>luggage</tt>.
     *
     * @return property value of luggage
     */
	public Money getLuggage() {
		return luggage;
	}
	
	/**
	 * Setter method for property <tt>luggage</tt>.
	 * 
	 * @param luggage value to be assigned to property luggage
     */
	public void setLuggage(Money luggage) {
		if (luggage == null) {
			this.luggage = new Money(0, 0);
		} else {
			this.luggage = luggage;
		}
	}

    /**
     * Getter method for property <tt>usePoint</tt>.
     *
     * @return property value of usePoint
     */
	public Money getUsePoint() {
		return usePoint;
	}
	
	/**
	 * Setter method for property <tt>usePoint</tt>.
	 * 
	 * @param usePoint value to be assigned to property usePoint
     */
	public void setUsePoint(Money usePoint) {
		if (usePoint == null) {
			this.usePoint = new Money(0, 0);
		} else {
			this.usePoint = usePoint;
		}
	}

    /**
     * Getter method for property <tt>oldPrice</tt>.
     *
     * @return property value of oldPrice
     */
	public Money getOldPrice() {
		return oldPrice;
	}
	
	/**
	 * Setter method for property <tt>oldPrice</tt>.
	 * 
	 * @param oldPrice value to be assigned to property oldPrice
     */
	public void setOldPrice(Money oldPrice) {
		if (oldPrice == null) {
			this.oldPrice = new Money(0, 0);
		} else {
			this.oldPrice = oldPrice;
		}
	}

    /**
     * Getter method for property <tt>soleCount</tt>.
     *
     * @return property value of soleCount
     */
	public int getSoleCount() {
		return soleCount;
	}
	
	/**
	 * Setter method for property <tt>soleCount</tt>.
	 * 
	 * @param soleCount value to be assigned to property soleCount
     */
	public void setSoleCount(int soleCount) {
		this.soleCount = soleCount;
	}

    /**
     * Getter method for property <tt>checkStatus</tt>.
     *
     * @return property value of checkStatus
     */
	public String getCheckStatus() {
		return checkStatus;
	}
	
	/**
	 * Setter method for property <tt>checkStatus</tt>.
	 * 
	 * @param checkStatus value to be assigned to property checkStatus
     */
	public void setCheckStatus(String checkStatus) {
		this.checkStatus = checkStatus;
	}

    /**
     * Getter method for property <tt>status</tt>.
     *
     * @return property value of status
     */
	public String getStatus() {
		return status;
	}
	
	/**
	 * Setter method for property <tt>status</tt>.
	 * 
	 * @param status value to be assigned to property status
     */
	public void setStatus(String status) {
		this.status = status;
	}

    /**
     * Getter method for property <tt>stock</tt>.
     *
     * @return property value of stock
     */
	public int getStock() {
		return stock;
	}
	
	/**
	 * Setter method for property <tt>stock</tt>.
	 * 
	 * @param stock value to be assigned to property stock
     */
	public void setStock(int stock) {
		this.stock = stock;
	}

    /**
     * Getter method for property <tt>productUrl</tt>.
     *
     * @return property value of productUrl
     */
	public String getProductUrl() {
		return productUrl;
	}
	
	/**
	 * Setter method for property <tt>productUrl</tt>.
	 * 
	 * @param productUrl value to be assigned to property productUrl
     */
	public void setProductUrl(String productUrl) {
		this.productUrl = productUrl;
	}

    /**
     * Getter method for property <tt>delFlg</tt>.
     *
     * @return property value of delFlg
     */
	public String getDelFlg() {
		return delFlg;
	}
	
	/**
	 * Setter method for property <tt>delFlg</tt>.
	 * 
	 * @param delFlg value to be assigned to property delFlg
     */
	public void setDelFlg(String delFlg) {
		this.delFlg = delFlg;
	}

    /**
     * Getter method for property <tt>recommendFlg</tt>.
     *
     * @return property value of recommendFlg
     */
	public String getRecommendFlg() {
		return recommendFlg;
	}
	
	/**
	 * Setter method for property <tt>recommendFlg</tt>.
	 * 
	 * @param recommendFlg value to be assigned to property recommendFlg
     */
	public void setRecommendFlg(String recommendFlg) {
		this.recommendFlg = recommendFlg;
	}

    /**
     * Getter method for property <tt>proportionReturn</tt>.
     *
     * @return property value of proportionReturn
     */
	public double getProportionReturn() {
		return proportionReturn;
	}
	
	/**
	 * Setter method for property <tt>proportionReturn</tt>.
	 * 
	 * @param proportionReturn value to be assigned to property proportionReturn
     */
	public void setProportionReturn(double proportionReturn) {
		this.proportionReturn = proportionReturn;
	}

    /**
     * Getter method for property <tt>proportionIntegral</tt>.
     *
     * @return property value of proportionIntegral
     */
	public double getProportionIntegral() {
		return proportionIntegral;
	}
	
	/**
	 * Setter method for property <tt>proportionIntegral</tt>.
	 * 
	 * @param proportionIntegral value to be assigned to property proportionIntegral
     */
	public void setProportionIntegral(double proportionIntegral) {
		this.proportionIntegral = proportionIntegral;
	}

    /**
     * Getter method for property <tt>creater</tt>.
     *
     * @return property value of creater
     */
	public String getCreater() {
		return creater;
	}
	
	/**
	 * Setter method for property <tt>creater</tt>.
	 * 
	 * @param creater value to be assigned to property creater
     */
	public void setCreater(String creater) {
		this.creater = creater;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>modifier</tt>.
     *
     * @return property value of modifier
     */
	public String getModifier() {
		return modifier;
	}
	
	/**
	 * Setter method for property <tt>modifier</tt>.
	 * 
	 * @param modifier value to be assigned to property modifier
     */
	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

    /**
     * Getter method for property <tt>memo</tt>.
     *
     * @return property value of memo
     */
	public String getMemo() {
		return memo;
	}
	
	/**
	 * Setter method for property <tt>memo</tt>.
	 * 
	 * @param memo value to be assigned to property memo
     */
	public void setMemo(String memo) {
		this.memo = memo;
	}
}
