/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.makeploy.common.dal.dataobject;

import com.onway.makeploy.common.dal.dataobject.BaseDO;

import java.util.Date;
import com.onway.common.lang.Money;

/**
 * A data object class directly models database table <tt>makeploy_team_income</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/makeploy_team_income.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: TeamIncomeDO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class TeamIncomeDO extends BaseDO {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>ID</tt>.
	 */
	private int id;

	/**
	 * This property corresponds to db column <tt>USER_ID</tt>.
	 */
	private String userId;

	/**
	 * This property corresponds to db column <tt>SELL_ACCOUT</tt>.
	 */
	private Money sellAccout = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>INCOME_ACCOUT</tt>.
	 */
	private Money incomeAccout = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>TEAM_SUM</tt>.
	 */
	private int teamSum;

	/**
	 * This property corresponds to db column <tt>TIME</tt>.
	 */
	private Date time;

	/**
	 * This property corresponds to db column <tt>CREATER</tt>.
	 */
	private String creater;

	/**
	 * This property corresponds to db column <tt>GMT_CREATE</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>MODIFIER</tt>.
	 */
	private String modifier;

	/**
	 * This property corresponds to db column <tt>GMT_MODIFIED</tt>.
	 */
	private Date gmtModified;

	/**
	 * This property corresponds to db column <tt>MEMO</tt>.
	 */
	private String memo;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public int getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(int id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>userId</tt>.
     *
     * @return property value of userId
     */
	public String getUserId() {
		return userId;
	}
	
	/**
	 * Setter method for property <tt>userId</tt>.
	 * 
	 * @param userId value to be assigned to property userId
     */
	public void setUserId(String userId) {
		this.userId = userId;
	}

    /**
     * Getter method for property <tt>sellAccout</tt>.
     *
     * @return property value of sellAccout
     */
	public Money getSellAccout() {
		return sellAccout;
	}
	
	/**
	 * Setter method for property <tt>sellAccout</tt>.
	 * 
	 * @param sellAccout value to be assigned to property sellAccout
     */
	public void setSellAccout(Money sellAccout) {
		if (sellAccout == null) {
			this.sellAccout = new Money(0, 0);
		} else {
			this.sellAccout = sellAccout;
		}
	}

    /**
     * Getter method for property <tt>incomeAccout</tt>.
     *
     * @return property value of incomeAccout
     */
	public Money getIncomeAccout() {
		return incomeAccout;
	}
	
	/**
	 * Setter method for property <tt>incomeAccout</tt>.
	 * 
	 * @param incomeAccout value to be assigned to property incomeAccout
     */
	public void setIncomeAccout(Money incomeAccout) {
		if (incomeAccout == null) {
			this.incomeAccout = new Money(0, 0);
		} else {
			this.incomeAccout = incomeAccout;
		}
	}

    /**
     * Getter method for property <tt>teamSum</tt>.
     *
     * @return property value of teamSum
     */
	public int getTeamSum() {
		return teamSum;
	}
	
	/**
	 * Setter method for property <tt>teamSum</tt>.
	 * 
	 * @param teamSum value to be assigned to property teamSum
     */
	public void setTeamSum(int teamSum) {
		this.teamSum = teamSum;
	}

    /**
     * Getter method for property <tt>time</tt>.
     *
     * @return property value of time
     */
	public Date getTime() {
		return time;
	}
	
	/**
	 * Setter method for property <tt>time</tt>.
	 * 
	 * @param time value to be assigned to property time
     */
	public void setTime(Date time) {
		this.time = time;
	}

    /**
     * Getter method for property <tt>creater</tt>.
     *
     * @return property value of creater
     */
	public String getCreater() {
		return creater;
	}
	
	/**
	 * Setter method for property <tt>creater</tt>.
	 * 
	 * @param creater value to be assigned to property creater
     */
	public void setCreater(String creater) {
		this.creater = creater;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>modifier</tt>.
     *
     * @return property value of modifier
     */
	public String getModifier() {
		return modifier;
	}
	
	/**
	 * Setter method for property <tt>modifier</tt>.
	 * 
	 * @param modifier value to be assigned to property modifier
     */
	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

    /**
     * Getter method for property <tt>memo</tt>.
     *
     * @return property value of memo
     */
	public String getMemo() {
		return memo;
	}
	
	/**
	 * Setter method for property <tt>memo</tt>.
	 * 
	 * @param memo value to be assigned to property memo
     */
	public void setMemo(String memo) {
		this.memo = memo;
	}
}
