/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.makeploy.common.dal.dataobject;

import com.onway.makeploy.common.dal.dataobject.BaseDO;

import java.util.Date;

/**
 * A data object class directly models database table <tt>makeploy_unionshop_check</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/makeploy_unionshop_check.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: UnionshopCheckDO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class UnionshopCheckDO extends BaseDO {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>ID</tt>.
	 */
	private int id;

	/**
	 * This property corresponds to db column <tt>USER_ID</tt>.
	 */
	private String userId;

	/**
	 * This property corresponds to db column <tt>SHOP_ID</tt>.
	 */
	private String shopId;

	/**
	 * This property corresponds to db column <tt>LINKMAN_NAME</tt>.
	 */
	private String linkmanName;

	/**
	 * This property corresponds to db column <tt>USER_CELL</tt>.
	 */
	private String userCell;

	/**
	 * This property corresponds to db column <tt>SHOP_NAME</tt>.
	 */
	private String shopName;

	/**
	 * This property corresponds to db column <tt>SHOP_DEC</tt>.
	 */
	private String shopDec;

	/**
	 * This property corresponds to db column <tt>SHOP_CELL</tt>.
	 */
	private String shopCell;

	/**
	 * This property corresponds to db column <tt>DISTRICT</tt>.
	 */
	private String district;

	/**
	 * This property corresponds to db column <tt>CITY</tt>.
	 */
	private String city;

	/**
	 * This property corresponds to db column <tt>PROVIENCE</tt>.
	 */
	private String provience;

	/**
	 * This property corresponds to db column <tt>ADDR</tt>.
	 */
	private String addr;

	/**
	 * This property corresponds to db column <tt>INDUSTRY</tt>.
	 */
	private String industry;

	/**
	 * This property corresponds to db column <tt>CHECK_STATUS</tt>.
	 */
	private String checkStatus;

	/**
	 * This property corresponds to db column <tt>CREATER</tt>.
	 */
	private String creater;

	/**
	 * This property corresponds to db column <tt>GMT_CREATE</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>MODIFIER</tt>.
	 */
	private String modifier;

	/**
	 * This property corresponds to db column <tt>GMT_MODIFIED</tt>.
	 */
	private Date gmtModified;

	/**
	 * This property corresponds to db column <tt>MEMO</tt>.
	 */
	private String memo;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public int getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(int id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>userId</tt>.
     *
     * @return property value of userId
     */
	public String getUserId() {
		return userId;
	}
	
	/**
	 * Setter method for property <tt>userId</tt>.
	 * 
	 * @param userId value to be assigned to property userId
     */
	public void setUserId(String userId) {
		this.userId = userId;
	}

    /**
     * Getter method for property <tt>shopId</tt>.
     *
     * @return property value of shopId
     */
	public String getShopId() {
		return shopId;
	}
	
	/**
	 * Setter method for property <tt>shopId</tt>.
	 * 
	 * @param shopId value to be assigned to property shopId
     */
	public void setShopId(String shopId) {
		this.shopId = shopId;
	}

    /**
     * Getter method for property <tt>linkmanName</tt>.
     *
     * @return property value of linkmanName
     */
	public String getLinkmanName() {
		return linkmanName;
	}
	
	/**
	 * Setter method for property <tt>linkmanName</tt>.
	 * 
	 * @param linkmanName value to be assigned to property linkmanName
     */
	public void setLinkmanName(String linkmanName) {
		this.linkmanName = linkmanName;
	}

    /**
     * Getter method for property <tt>userCell</tt>.
     *
     * @return property value of userCell
     */
	public String getUserCell() {
		return userCell;
	}
	
	/**
	 * Setter method for property <tt>userCell</tt>.
	 * 
	 * @param userCell value to be assigned to property userCell
     */
	public void setUserCell(String userCell) {
		this.userCell = userCell;
	}

    /**
     * Getter method for property <tt>shopName</tt>.
     *
     * @return property value of shopName
     */
	public String getShopName() {
		return shopName;
	}
	
	/**
	 * Setter method for property <tt>shopName</tt>.
	 * 
	 * @param shopName value to be assigned to property shopName
     */
	public void setShopName(String shopName) {
		this.shopName = shopName;
	}

    /**
     * Getter method for property <tt>shopDec</tt>.
     *
     * @return property value of shopDec
     */
	public String getShopDec() {
		return shopDec;
	}
	
	/**
	 * Setter method for property <tt>shopDec</tt>.
	 * 
	 * @param shopDec value to be assigned to property shopDec
     */
	public void setShopDec(String shopDec) {
		this.shopDec = shopDec;
	}

    /**
     * Getter method for property <tt>shopCell</tt>.
     *
     * @return property value of shopCell
     */
	public String getShopCell() {
		return shopCell;
	}
	
	/**
	 * Setter method for property <tt>shopCell</tt>.
	 * 
	 * @param shopCell value to be assigned to property shopCell
     */
	public void setShopCell(String shopCell) {
		this.shopCell = shopCell;
	}

    /**
     * Getter method for property <tt>district</tt>.
     *
     * @return property value of district
     */
	public String getDistrict() {
		return district;
	}
	
	/**
	 * Setter method for property <tt>district</tt>.
	 * 
	 * @param district value to be assigned to property district
     */
	public void setDistrict(String district) {
		this.district = district;
	}

    /**
     * Getter method for property <tt>city</tt>.
     *
     * @return property value of city
     */
	public String getCity() {
		return city;
	}
	
	/**
	 * Setter method for property <tt>city</tt>.
	 * 
	 * @param city value to be assigned to property city
     */
	public void setCity(String city) {
		this.city = city;
	}

    /**
     * Getter method for property <tt>provience</tt>.
     *
     * @return property value of provience
     */
	public String getProvience() {
		return provience;
	}
	
	/**
	 * Setter method for property <tt>provience</tt>.
	 * 
	 * @param provience value to be assigned to property provience
     */
	public void setProvience(String provience) {
		this.provience = provience;
	}

    /**
     * Getter method for property <tt>addr</tt>.
     *
     * @return property value of addr
     */
	public String getAddr() {
		return addr;
	}
	
	/**
	 * Setter method for property <tt>addr</tt>.
	 * 
	 * @param addr value to be assigned to property addr
     */
	public void setAddr(String addr) {
		this.addr = addr;
	}

    /**
     * Getter method for property <tt>industry</tt>.
     *
     * @return property value of industry
     */
	public String getIndustry() {
		return industry;
	}
	
	/**
	 * Setter method for property <tt>industry</tt>.
	 * 
	 * @param industry value to be assigned to property industry
     */
	public void setIndustry(String industry) {
		this.industry = industry;
	}

    /**
     * Getter method for property <tt>checkStatus</tt>.
     *
     * @return property value of checkStatus
     */
	public String getCheckStatus() {
		return checkStatus;
	}
	
	/**
	 * Setter method for property <tt>checkStatus</tt>.
	 * 
	 * @param checkStatus value to be assigned to property checkStatus
     */
	public void setCheckStatus(String checkStatus) {
		this.checkStatus = checkStatus;
	}

    /**
     * Getter method for property <tt>creater</tt>.
     *
     * @return property value of creater
     */
	public String getCreater() {
		return creater;
	}
	
	/**
	 * Setter method for property <tt>creater</tt>.
	 * 
	 * @param creater value to be assigned to property creater
     */
	public void setCreater(String creater) {
		this.creater = creater;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>modifier</tt>.
     *
     * @return property value of modifier
     */
	public String getModifier() {
		return modifier;
	}
	
	/**
	 * Setter method for property <tt>modifier</tt>.
	 * 
	 * @param modifier value to be assigned to property modifier
     */
	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

    /**
     * Getter method for property <tt>memo</tt>.
     *
     * @return property value of memo
     */
	public String getMemo() {
		return memo;
	}
	
	/**
	 * Setter method for property <tt>memo</tt>.
	 * 
	 * @param memo value to be assigned to property memo
     */
	public void setMemo(String memo) {
		this.memo = memo;
	}
}
