/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.makeploy.common.dal.dataobject;

import com.onway.makeploy.common.dal.dataobject.BaseDO;

import java.util.Date;
import com.onway.common.lang.Money;

/**
 * A data object class directly models database table <tt>makeploy_user</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/makeploy_user.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: UserDO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class UserDO extends BaseDO {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>ID</tt>.
	 */
	private int id;

	/**
	 * This property corresponds to db column <tt>USER_ID</tt>.
	 */
	private String userId;

	/**
	 * This property corresponds to db column <tt>WECHAT_ID</tt>.
	 */
	private String wechatId;

	/**
	 * This property corresponds to db column <tt>PROMOTE_ID</tt>.
	 */
	private String promoteId;

	/**
	 * This property corresponds to db column <tt>SHOP_ID</tt>.
	 */
	private String shopId;

	/**
	 * This property corresponds to db column <tt>COMMERCE_ID</tt>.
	 */
	private String commerceId;

	/**
	 * This property corresponds to db column <tt>USER_NAME</tt>.
	 */
	private String userName;

	/**
	 * This property corresponds to db column <tt>USER_NUM</tt>.
	 */
	private String userNum;

	/**
	 * This property corresponds to db column <tt>CELL</tt>.
	 */
	private String cell;

	/**
	 * This property corresponds to db column <tt>NICK_NAME</tt>.
	 */
	private String nickName;

	/**
	 * This property corresponds to db column <tt>SEX</tt>.
	 */
	private String sex;

	/**
	 * This property corresponds to db column <tt>HEAD_URL</tt>.
	 */
	private String headUrl;

	/**
	 * This property corresponds to db column <tt>PASS_WORD</tt>.
	 */
	private String passWord;

	/**
	 * This property corresponds to db column <tt>CERT_TYPE</tt>.
	 */
	private String certType;

	/**
	 * This property corresponds to db column <tt>CERT_NO</tt>.
	 */
	private String certNo;

	/**
	 * This property corresponds to db column <tt>CONSUME_ACCOUT</tt>.
	 */
	private Money consumeAccout = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>DIVIDEND_ACCOUT</tt>.
	 */
	private Money dividendAccout = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>POINT_ACCOUT</tt>.
	 */
	private int pointAccout;

	/**
	 * This property corresponds to db column <tt>WITHDRAW_ACCOUT</tt>.
	 */
	private Money withdrawAccout = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>BALANCE</tt>.
	 */
	private Money balance = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>TOTAL_BALANCE</tt>.
	 */
	private Money totalBalance = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>INCOME_WEEK</tt>.
	 */
	private Money incomeWeek = new Money(0, 0);

	/**
	 * This property corresponds to db column <tt>HIGH_USER_ID</tt>.
	 */
	private String highUserId;

	/**
	 * This property corresponds to db column <tt>QR_URL</tt>.
	 */
	private String qrUrl;

	/**
	 * This property corresponds to db column <tt>CREATER</tt>.
	 */
	private String creater;

	/**
	 * This property corresponds to db column <tt>GMT_CREATE</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>MODIFIER</tt>.
	 */
	private String modifier;

	/**
	 * This property corresponds to db column <tt>GMT_MODIFIED</tt>.
	 */
	private Date gmtModified;

	/**
	 * This property corresponds to db column <tt>MEMO</tt>.
	 */
	private String memo;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public int getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(int id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>userId</tt>.
     *
     * @return property value of userId
     */
	public String getUserId() {
		return userId;
	}
	
	/**
	 * Setter method for property <tt>userId</tt>.
	 * 
	 * @param userId value to be assigned to property userId
     */
	public void setUserId(String userId) {
		this.userId = userId;
	}

    /**
     * Getter method for property <tt>wechatId</tt>.
     *
     * @return property value of wechatId
     */
	public String getWechatId() {
		return wechatId;
	}
	
	/**
	 * Setter method for property <tt>wechatId</tt>.
	 * 
	 * @param wechatId value to be assigned to property wechatId
     */
	public void setWechatId(String wechatId) {
		this.wechatId = wechatId;
	}

    /**
     * Getter method for property <tt>promoteId</tt>.
     *
     * @return property value of promoteId
     */
	public String getPromoteId() {
		return promoteId;
	}
	
	/**
	 * Setter method for property <tt>promoteId</tt>.
	 * 
	 * @param promoteId value to be assigned to property promoteId
     */
	public void setPromoteId(String promoteId) {
		this.promoteId = promoteId;
	}

    /**
     * Getter method for property <tt>shopId</tt>.
     *
     * @return property value of shopId
     */
	public String getShopId() {
		return shopId;
	}
	
	/**
	 * Setter method for property <tt>shopId</tt>.
	 * 
	 * @param shopId value to be assigned to property shopId
     */
	public void setShopId(String shopId) {
		this.shopId = shopId;
	}

    /**
     * Getter method for property <tt>commerceId</tt>.
     *
     * @return property value of commerceId
     */
	public String getCommerceId() {
		return commerceId;
	}
	
	/**
	 * Setter method for property <tt>commerceId</tt>.
	 * 
	 * @param commerceId value to be assigned to property commerceId
     */
	public void setCommerceId(String commerceId) {
		this.commerceId = commerceId;
	}

    /**
     * Getter method for property <tt>userName</tt>.
     *
     * @return property value of userName
     */
	public String getUserName() {
		return userName;
	}
	
	/**
	 * Setter method for property <tt>userName</tt>.
	 * 
	 * @param userName value to be assigned to property userName
     */
	public void setUserName(String userName) {
		this.userName = userName;
	}

    /**
     * Getter method for property <tt>userNum</tt>.
     *
     * @return property value of userNum
     */
	public String getUserNum() {
		return userNum;
	}
	
	/**
	 * Setter method for property <tt>userNum</tt>.
	 * 
	 * @param userNum value to be assigned to property userNum
     */
	public void setUserNum(String userNum) {
		this.userNum = userNum;
	}

    /**
     * Getter method for property <tt>cell</tt>.
     *
     * @return property value of cell
     */
	public String getCell() {
		return cell;
	}
	
	/**
	 * Setter method for property <tt>cell</tt>.
	 * 
	 * @param cell value to be assigned to property cell
     */
	public void setCell(String cell) {
		this.cell = cell;
	}

    /**
     * Getter method for property <tt>nickName</tt>.
     *
     * @return property value of nickName
     */
	public String getNickName() {
		return nickName;
	}
	
	/**
	 * Setter method for property <tt>nickName</tt>.
	 * 
	 * @param nickName value to be assigned to property nickName
     */
	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

    /**
     * Getter method for property <tt>sex</tt>.
     *
     * @return property value of sex
     */
	public String getSex() {
		return sex;
	}
	
	/**
	 * Setter method for property <tt>sex</tt>.
	 * 
	 * @param sex value to be assigned to property sex
     */
	public void setSex(String sex) {
		this.sex = sex;
	}

    /**
     * Getter method for property <tt>headUrl</tt>.
     *
     * @return property value of headUrl
     */
	public String getHeadUrl() {
		return headUrl;
	}
	
	/**
	 * Setter method for property <tt>headUrl</tt>.
	 * 
	 * @param headUrl value to be assigned to property headUrl
     */
	public void setHeadUrl(String headUrl) {
		this.headUrl = headUrl;
	}

    /**
     * Getter method for property <tt>passWord</tt>.
     *
     * @return property value of passWord
     */
	public String getPassWord() {
		return passWord;
	}
	
	/**
	 * Setter method for property <tt>passWord</tt>.
	 * 
	 * @param passWord value to be assigned to property passWord
     */
	public void setPassWord(String passWord) {
		this.passWord = passWord;
	}

    /**
     * Getter method for property <tt>certType</tt>.
     *
     * @return property value of certType
     */
	public String getCertType() {
		return certType;
	}
	
	/**
	 * Setter method for property <tt>certType</tt>.
	 * 
	 * @param certType value to be assigned to property certType
     */
	public void setCertType(String certType) {
		this.certType = certType;
	}

    /**
     * Getter method for property <tt>certNo</tt>.
     *
     * @return property value of certNo
     */
	public String getCertNo() {
		return certNo;
	}
	
	/**
	 * Setter method for property <tt>certNo</tt>.
	 * 
	 * @param certNo value to be assigned to property certNo
     */
	public void setCertNo(String certNo) {
		this.certNo = certNo;
	}

    /**
     * Getter method for property <tt>consumeAccout</tt>.
     *
     * @return property value of consumeAccout
     */
	public Money getConsumeAccout() {
		return consumeAccout;
	}
	
	/**
	 * Setter method for property <tt>consumeAccout</tt>.
	 * 
	 * @param consumeAccout value to be assigned to property consumeAccout
     */
	public void setConsumeAccout(Money consumeAccout) {
		if (consumeAccout == null) {
			this.consumeAccout = new Money(0, 0);
		} else {
			this.consumeAccout = consumeAccout;
		}
	}

    /**
     * Getter method for property <tt>dividendAccout</tt>.
     *
     * @return property value of dividendAccout
     */
	public Money getDividendAccout() {
		return dividendAccout;
	}
	
	/**
	 * Setter method for property <tt>dividendAccout</tt>.
	 * 
	 * @param dividendAccout value to be assigned to property dividendAccout
     */
	public void setDividendAccout(Money dividendAccout) {
		if (dividendAccout == null) {
			this.dividendAccout = new Money(0, 0);
		} else {
			this.dividendAccout = dividendAccout;
		}
	}

    /**
     * Getter method for property <tt>pointAccout</tt>.
     *
     * @return property value of pointAccout
     */
	public int getPointAccout() {
		return pointAccout;
	}
	
	/**
	 * Setter method for property <tt>pointAccout</tt>.
	 * 
	 * @param pointAccout value to be assigned to property pointAccout
     */
	public void setPointAccout(int pointAccout) {
		this.pointAccout = pointAccout;
	}

    /**
     * Getter method for property <tt>withdrawAccout</tt>.
     *
     * @return property value of withdrawAccout
     */
	public Money getWithdrawAccout() {
		return withdrawAccout;
	}
	
	/**
	 * Setter method for property <tt>withdrawAccout</tt>.
	 * 
	 * @param withdrawAccout value to be assigned to property withdrawAccout
     */
	public void setWithdrawAccout(Money withdrawAccout) {
		if (withdrawAccout == null) {
			this.withdrawAccout = new Money(0, 0);
		} else {
			this.withdrawAccout = withdrawAccout;
		}
	}

    /**
     * Getter method for property <tt>balance</tt>.
     *
     * @return property value of balance
     */
	public Money getBalance() {
		return balance;
	}
	
	/**
	 * Setter method for property <tt>balance</tt>.
	 * 
	 * @param balance value to be assigned to property balance
     */
	public void setBalance(Money balance) {
		if (balance == null) {
			this.balance = new Money(0, 0);
		} else {
			this.balance = balance;
		}
	}

    /**
     * Getter method for property <tt>totalBalance</tt>.
     *
     * @return property value of totalBalance
     */
	public Money getTotalBalance() {
		return totalBalance;
	}
	
	/**
	 * Setter method for property <tt>totalBalance</tt>.
	 * 
	 * @param totalBalance value to be assigned to property totalBalance
     */
	public void setTotalBalance(Money totalBalance) {
		if (totalBalance == null) {
			this.totalBalance = new Money(0, 0);
		} else {
			this.totalBalance = totalBalance;
		}
	}

    /**
     * Getter method for property <tt>incomeWeek</tt>.
     *
     * @return property value of incomeWeek
     */
	public Money getIncomeWeek() {
		return incomeWeek;
	}
	
	/**
	 * Setter method for property <tt>incomeWeek</tt>.
	 * 
	 * @param incomeWeek value to be assigned to property incomeWeek
     */
	public void setIncomeWeek(Money incomeWeek) {
		if (incomeWeek == null) {
			this.incomeWeek = new Money(0, 0);
		} else {
			this.incomeWeek = incomeWeek;
		}
	}

    /**
     * Getter method for property <tt>highUserId</tt>.
     *
     * @return property value of highUserId
     */
	public String getHighUserId() {
		return highUserId;
	}
	
	/**
	 * Setter method for property <tt>highUserId</tt>.
	 * 
	 * @param highUserId value to be assigned to property highUserId
     */
	public void setHighUserId(String highUserId) {
		this.highUserId = highUserId;
	}

    /**
     * Getter method for property <tt>qrUrl</tt>.
     *
     * @return property value of qrUrl
     */
	public String getQrUrl() {
		return qrUrl;
	}
	
	/**
	 * Setter method for property <tt>qrUrl</tt>.
	 * 
	 * @param qrUrl value to be assigned to property qrUrl
     */
	public void setQrUrl(String qrUrl) {
		this.qrUrl = qrUrl;
	}

    /**
     * Getter method for property <tt>creater</tt>.
     *
     * @return property value of creater
     */
	public String getCreater() {
		return creater;
	}
	
	/**
	 * Setter method for property <tt>creater</tt>.
	 * 
	 * @param creater value to be assigned to property creater
     */
	public void setCreater(String creater) {
		this.creater = creater;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>modifier</tt>.
     *
     * @return property value of modifier
     */
	public String getModifier() {
		return modifier;
	}
	
	/**
	 * Setter method for property <tt>modifier</tt>.
	 * 
	 * @param modifier value to be assigned to property modifier
     */
	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

    /**
     * Getter method for property <tt>memo</tt>.
     *
     * @return property value of memo
     */
	public String getMemo() {
		return memo;
	}
	
	/**
	 * Setter method for property <tt>memo</tt>.
	 * 
	 * @param memo value to be assigned to property memo
     */
	public void setMemo(String memo) {
		this.memo = memo;
	}
}
