/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.makeploy.common.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.onway.makeploy.common.dal.daointerface.AgentDAO;

import com.onway.makeploy.common.dal.dataobject.AgentDO;
import org.springframework.dao.DataAccessException;
import java.util.List;
import com.onway.common.lang.Money;
import java.util.Map;
import java.util.HashMap;

/**
 * An ibatis based implementation of dao interface <tt>com.onway.makeploy.common.dal.daointerface.AgentDAO</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/makeploy_agent.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: IbatisAgentDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class IbatisAgentDAO extends SqlMapClientDaoSupport implements AgentDAO {
	/**
	 *  Insert one <tt>AgentDO</tt> object to DB table <tt>makeploy_agent</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into makeploy_agent(ID,USER_ID,USER_NAME,CELL,PROVINCE,CITY,DISTRICT,AREA_INCOME,CHECK_OUT,GMT_CREATE,MODIFIER,GMT_MODIFIED,MEMO) values (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ?, CURRENT_TIMESTAMP, ?)</tt>
	 *
	 *	@param agent
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int addAgent(AgentDO agent) throws DataAccessException {
    	if (agent == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert("MS-AGENT-ADD-AGENT", agent);

        return agent.getId();
    }

	/**
	 *  Query DB table <tt>makeploy_agent</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_agent</tt>
	 *
	 *	@param userId
	 *	@param cell
	 *	@param province
	 *	@param city
	 *	@param district
	 *	@return AgentDO
	 *	@throws DataAccessException
	 */	 
    public AgentDO selectAll(String userId, String cell, String province, String city, String district) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("userId", userId);
        param.put("cell", cell);
        param.put("province", province);
        param.put("city", city);
        param.put("district", district);

        return (AgentDO) getSqlMapClientTemplate().queryForObject("MS-AGENT-SELECT-ALL", param);

    }

	/**
	 *  Query DB table <tt>makeploy_agent</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_agent</tt>
	 *
	 *	@param userId
	 *	@param cell
	 *	@param province
	 *	@param city
	 *	@param district
	 *	@param offset
	 *	@param limit
	 *	@return List<AgentDO>
	 *	@throws DataAccessException
	 */	 
    public List<AgentDO> selectAgentInfo(String userId, String cell, String province, String city, String district, Integer offset, Integer limit) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("userId", userId);
        param.put("cell", cell);
        param.put("province", province);
        param.put("city", city);
        param.put("district", district);
        param.put("offset", offset);
        param.put("limit", limit);

        return getSqlMapClientTemplate().queryForList("MS-AGENT-SELECT-AGENT-INFO", param);

    }

	/**
	 *  Update DB table <tt>makeploy_agent</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_agent set CHECK_OUT=CURRENT_TIMESTAMP, AREA_INCOME=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (USER_ID = ?)</tt>
	 *
	 *	@param areaIncome
	 *	@param userId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateCheckout(Money areaIncome, String userId) throws DataAccessException {
        Map<String,Object> param = new HashMap<String,Object>();

        param.put("areaIncome", areaIncome);
        param.put("userId", userId);

        return getSqlMapClientTemplate().update("MS-AGENT-UPDATE-CHECKOUT", param);
    }

	/**
	 *  Update DB table <tt>makeploy_agent</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_agent set AREA_INCOME=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (USER_ID = ?)</tt>
	 *
	 *	@param areaIncome
	 *	@param userId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateOutMoney(Money areaIncome, String userId) throws DataAccessException {
        Map<String,Object> param = new HashMap<String,Object>();

        param.put("areaIncome", areaIncome);
        param.put("userId", userId);

        return getSqlMapClientTemplate().update("MS-AGENT-UPDATE-OUT-MONEY", param);
    }

	/**
	 *  Query DB table <tt>makeploy_agent</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select count(1) from makeploy_agent</tt>
	 *
	 *	@param userId
	 *	@param cell
	 *	@param province
	 *	@param city
	 *	@param district
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long count(String userId, String cell, String province, String city, String district) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("userId", userId);
        param.put("cell", cell);
        param.put("province", province);
        param.put("city", city);
        param.put("district", district);

	    Long retObj = (Long) getSqlMapClientTemplate().queryForObject("MS-AGENT-COUNT", param);

		if (retObj == null) {
		    return 0;
		} else {
		    return retObj.longValue();
		}

    }

}