/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.makeploy.common.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.onway.makeploy.common.dal.daointerface.BorrowMoneyDAO;

import com.onway.makeploy.common.dal.dataobject.BorrowMoneyDO;
import java.util.List;
import org.springframework.dao.DataAccessException;
import java.util.Map;
import java.util.HashMap;

/**
 * An ibatis based implementation of dao interface <tt>com.onway.makeploy.common.dal.daointerface.BorrowMoneyDAO</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/makeploy_borrow_money.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: IbatisBorrowMoneyDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class IbatisBorrowMoneyDAO extends SqlMapClientDaoSupport implements BorrowMoneyDAO {
	/**
	 *  Query DB table <tt>makeploy_borrow_money</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_borrow_money</tt>
	 *
	 *	@param state
	 *	@param offset
	 *	@param limit
	 *	@return List<BorrowMoneyDO>
	 *	@throws DataAccessException
	 */	 
    public List<BorrowMoneyDO> selectInfoByState(String state, Integer offset, Integer limit) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("state", state);
        param.put("offset", offset);
        param.put("limit", limit);

        return getSqlMapClientTemplate().queryForList("MS-BORROW-MONEY-SELECT-INFO-BY-STATE", param);

    }

	/**
	 *  Query DB table <tt>makeploy_borrow_money</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select count(1) from makeploy_borrow_money</tt>
	 *
	 *	@param state
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long selectInfoCount(String state) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("state", state);

	    Long retObj = (Long) getSqlMapClientTemplate().queryForObject("MS-BORROW-MONEY-SELECT-INFO-COUNT", param);

		if (retObj == null) {
		    return 0;
		} else {
		    return retObj.longValue();
		}

    }

	/**
	 *  Query DB table <tt>makeploy_borrow_money</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_borrow_money where (BORROW_ID = ?)</tt>
	 *
	 *	@param borrowId
	 *	@return BorrowMoneyDO
	 *	@throws DataAccessException
	 */	 
    public BorrowMoneyDO selectByBorrowId(String borrowId) throws DataAccessException {

 
        return (BorrowMoneyDO) getSqlMapClientTemplate().queryForObject("MS-BORROW-MONEY-SELECT-BY-BORROW-ID", borrowId);

    }

	/**
	 *  Update DB table <tt>makeploy_borrow_money</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_borrow_money set BORROW_STATE=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (BORROW_ID = ?)</tt>
	 *
	 *	@param borrowState
	 *	@param borrowId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int modifyState(String borrowState, String borrowId) throws DataAccessException {
        Map<String,Object> param = new HashMap<String,Object>();

        param.put("borrowState", borrowState);
        param.put("borrowId", borrowId);

        return getSqlMapClientTemplate().update("MS-BORROW-MONEY-MODIFY-STATE", param);
    }

}