/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.makeploy.common.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.onway.makeploy.common.dal.daointerface.CollectionDAO;

import com.onway.makeploy.common.dal.dataobject.CollectionDO;
import java.util.List;
import org.springframework.dao.DataAccessException;
import java.util.Map;
import java.util.HashMap;

/**
 * An ibatis based implementation of dao interface <tt>com.onway.makeploy.common.dal.daointerface.CollectionDAO</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/makeploy_collection.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: IbatisCollectionDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class IbatisCollectionDAO extends SqlMapClientDaoSupport implements CollectionDAO {
	/**
	 *  Query DB table <tt>makeploy_collection</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_collection</tt>
	 *
	 *	@param userId
	 *	@param type
	 *	@param status
	 *	@param startRow
	 *	@param pageSize
	 *	@return List<CollectionDO>
	 *	@throws DataAccessException
	 */	 
    public List<CollectionDO> selectCollectionInfoByUserIdAndTypeAndStatus(String userId, String type, String status, Integer startRow, Integer pageSize) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("userId", userId);
        param.put("type", type);
        param.put("status", status);
        param.put("startRow", startRow);
        param.put("pageSize", pageSize);

        return getSqlMapClientTemplate().queryForList("MS-COLLECTION-SELECT-COLLECTION-INFO-BY-USER-ID-AND-TYPE-AND-STATUS", param);

    }

	/**
	 *  Query DB table <tt>makeploy_collection</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_collection</tt>
	 *
	 *	@param userId
	 *	@param productNo
	 *	@param shopId
	 *	@return CollectionDO
	 *	@throws DataAccessException
	 */	 
    public CollectionDO selectCollectionInfoByUserIdAndProductNoAndShopId(String userId, String productNo, String shopId) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("userId", userId);
        param.put("productNo", productNo);
        param.put("shopId", shopId);

        return (CollectionDO) getSqlMapClientTemplate().queryForObject("MS-COLLECTION-SELECT-COLLECTION-INFO-BY-USER-ID-AND-PRODUCT-NO-AND-SHOP-ID", param);

    }

	/**
	 *  Query DB table <tt>makeploy_collection</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_collection</tt>
	 *
	 *	@param userId
	 *	@param type
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int selectCollectionCountByUserIdAndType(String userId, String type) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("userId", userId);
        param.put("type", type);

	    Integer retObj = (Integer) getSqlMapClientTemplate().queryForObject("MS-COLLECTION-SELECT-COLLECTION-COUNT-BY-USER-ID-AND-TYPE", param);

		if (retObj == null) {
		    return 0;
		} else {
		    return retObj.intValue();
		}

    }

	/**
	 *  Query DB table <tt>makeploy_collection</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_collection</tt>
	 *
	 *	@param userId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int selectCollectionCount(String userId) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("userId", userId);

	    Integer retObj = (Integer) getSqlMapClientTemplate().queryForObject("MS-COLLECTION-SELECT-COLLECTION-COUNT", param);

		if (retObj == null) {
		    return 0;
		} else {
		    return retObj.intValue();
		}

    }

	/**
	 *  Insert one <tt>CollectionDO</tt> object to DB table <tt>makeploy_collection</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into makeploy_collection(ID,USER_ID,PRODUCT_NO,SHOP_ID,TYPE,STATUS,CREATER,GMT_CREATE,MODIFIER,GMT_MODIFIED,MEMO) values (?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, ?, CURRENT_TIMESTAMP, ?)</tt>
	 *
	 *	@param collection
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int addCollection(CollectionDO collection) throws DataAccessException {
    	if (collection == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert("MS-COLLECTION-ADD-COLLECTION", collection);

        return collection.getId();
    }

	/**
	 *  Update DB table <tt>makeploy_collection</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_collection set STATUS=1, GMT_MODIFIED=CURRENT_TIMESTAMP where ((USER_ID = ?) AND (PRODUCT_NO = ?) AND (SHOP_ID = ?) AND (TYPE = 0))</tt>
	 *
	 *	@param collection
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int changeGoodsCollectionStatus(CollectionDO collection) throws DataAccessException {
    	if (collection == null) {
    		throw new IllegalArgumentException("Can't update by a null data object.");
    	}


        return getSqlMapClientTemplate().update("MS-COLLECTION-CHANGE-GOODS-COLLECTION-STATUS", collection);
    }

	/**
	 *  Update DB table <tt>makeploy_collection</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_collection set STATUS=1, GMT_MODIFIED=CURRENT_TIMESTAMP where ((USER_ID = ?) AND (SHOP_ID = ?) AND (TYPE = 1))</tt>
	 *
	 *	@param collection
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int changeShopCollectionStatus(CollectionDO collection) throws DataAccessException {
    	if (collection == null) {
    		throw new IllegalArgumentException("Can't update by a null data object.");
    	}


        return getSqlMapClientTemplate().update("MS-COLLECTION-CHANGE-SHOP-COLLECTION-STATUS", collection);
    }

}