/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.makeploy.common.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.onway.makeploy.common.dal.daointerface.CommerceCheckDAO;

import com.onway.makeploy.common.dal.dataobject.CommerceCheckDO;
import java.util.List;
import org.springframework.dao.DataAccessException;
import java.util.Map;
import java.util.HashMap;

/**
 * An ibatis based implementation of dao interface <tt>com.onway.makeploy.common.dal.daointerface.CommerceCheckDAO</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/makeploy_commerce_check.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: IbatisCommerceCheckDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class IbatisCommerceCheckDAO extends SqlMapClientDaoSupport implements CommerceCheckDAO {
	/**
	 *  Query DB table <tt>makeploy_commerce_check</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_commerce_check</tt>
	 *
	 *	@param offset
	 *	@param limit
	 *	@return List<CommerceCheckDO>
	 *	@throws DataAccessException
	 */	 
    public List<CommerceCheckDO> selectAllCommerceCheck(Integer offset, Integer limit) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("offset", offset);
        param.put("limit", limit);

        return getSqlMapClientTemplate().queryForList("MS-COMMERCE-CHECK-SELECT-ALL-COMMERCE-CHECK", param);

    }

	/**
	 *  Update DB table <tt>makeploy_commerce_check</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_commerce_check set USER_NAME=?, USER_CELL=?, USER_JOB=?, CARD_ADDR=?, NOW_ADDR=?, GMT_MODIFIED=CURRENT_TIMESTAMP where ((USER_ID = ?) AND (COMMERCE_ID = ?))</tt>
	 *
	 *	@param userName
	 *	@param userCell
	 *	@param userJob
	 *	@param cardAddr
	 *	@param nowAddr
	 *	@param userId
	 *	@param commerceId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int changeCommerceUserInfo(String userName, String userCell, String userJob, String cardAddr, String nowAddr, String userId, String commerceId) throws DataAccessException {
        Map<String,Object> param = new HashMap<String,Object>();

        param.put("userName", userName);
        param.put("userCell", userCell);
        param.put("userJob", userJob);
        param.put("cardAddr", cardAddr);
        param.put("nowAddr", nowAddr);
        param.put("userId", userId);
        param.put("commerceId", commerceId);

        return getSqlMapClientTemplate().update("MS-COMMERCE-CHECK-CHANGE-COMMERCE-USER-INFO", param);
    }

	/**
	 *  Query DB table <tt>makeploy_commerce_check</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select count(1) from makeploy_commerce_check</tt>
	 *
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int countitmes() throws DataAccessException {


	    Integer retObj = (Integer) getSqlMapClientTemplate().queryForObject("MS-COMMERCE-CHECK-COUNTITMES", null);

		if (retObj == null) {
		    return 0;
		} else {
		    return retObj.intValue();
		}

    }

	/**
	 *  Update DB table <tt>makeploy_commerce_check</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_commerce_check set STATUS=?, GMT_MODIFIED=CURRENT_TIMESTAMP where ((USER_ID = ?) AND (COMMERCE_ID = ?))</tt>
	 *
	 *	@param status
	 *	@param userId
	 *	@param commerceId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateOldCommerceCheck(String status, String userId, String commerceId) throws DataAccessException {
        Map<String,Object> param = new HashMap<String,Object>();

        param.put("status", status);
        param.put("userId", userId);
        param.put("commerceId", commerceId);

        return getSqlMapClientTemplate().update("MS-COMMERCE-CHECK-UPDATE-OLD-COMMERCE-CHECK", param);
    }

	/**
	 *  Query DB table <tt>makeploy_commerce_check</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_commerce_check</tt>
	 *
	 *	@param userId
	 *	@param commerceId
	 *	@return CommerceCheckDO
	 *	@throws DataAccessException
	 */	 
    public CommerceCheckDO selectMyCommerceCheck(String userId, String commerceId) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("userId", userId);
        param.put("commerceId", commerceId);

        return (CommerceCheckDO) getSqlMapClientTemplate().queryForObject("MS-COMMERCE-CHECK-SELECT-MY-COMMERCE-CHECK", param);

    }

	/**
	 *  Insert one <tt>CommerceCheckDO</tt> object to DB table <tt>makeploy_commerce_check</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into makeploy_commerce_check(ID,USER_ID,COMMERCE_ID,USER_NAME,USER_CELL,USER_JOB,CARD_ADDR,NOW_ADDR,MESSAGES,STATUS,CREATER,GMT_CREATE,MODIFIER,GMT_MODIFIED,MEMO) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, ?, CURRENT_TIMESTAMP, ?)</tt>
	 *
	 *	@param commerceCheck
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int addCommerceCheck(CommerceCheckDO commerceCheck) throws DataAccessException {
    	if (commerceCheck == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert("MS-COMMERCE-CHECK-ADD-COMMERCE-CHECK", commerceCheck);

        return commerceCheck.getId();
    }

	/**
	 *  Update DB table <tt>makeploy_commerce_check</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_commerce_check set STATUS=?, GMT_MODIFIED=CURRENT_TIMESTAMP where ((USER_ID = ?) AND (COMMERCE_ID = ?))</tt>
	 *
	 *	@param commerceCheck
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateCommerceCheck(CommerceCheckDO commerceCheck) throws DataAccessException {
    	if (commerceCheck == null) {
    		throw new IllegalArgumentException("Can't update by a null data object.");
    	}


        return getSqlMapClientTemplate().update("MS-COMMERCE-CHECK-UPDATE-COMMERCE-CHECK", commerceCheck);
    }

}