/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.makeploy.common.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.onway.makeploy.common.dal.daointerface.ActivityDAO;

import com.onway.makeploy.common.dal.dataobject.ActivityDO;
import java.util.List;
import org.springframework.dao.DataAccessException;
import java.util.Map;
import java.util.HashMap;

/**
 * An ibatis based implementation of dao interface <tt>com.onway.makeploy.common.dal.daointerface.ActivityDAO</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/makeploy_activity.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: IbatisActivityDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class IbatisActivityDAO extends SqlMapClientDaoSupport implements ActivityDAO {
	/**
	 *  Query DB table <tt>makeploy_activity</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_activity</tt>
	 *
	 *	@param type
	 *	@return List<ActivityDO>
	 *	@throws DataAccessException
	 */	 
    public List<ActivityDO> selectInfoByType(String type) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("type", type);

        return getSqlMapClientTemplate().queryForList("MS-ACTIVITY-SELECT-INFO-BY-TYPE", param);

    }

	/**
	 *  Insert one <tt>ActivityDO</tt> object to DB table <tt>makeploy_activity</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into makeploy_activity(ID,TITLE,INFO,TYPE,SUB_TYPE,POSTER,URL,STATE,NUM,CREATER,GMT_CREATE,MODIFIER,GMT_MODIFIED,MEMO) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, ?, CURRENT_TIMESTAMP, ?)</tt>
	 *
	 *	@param activity
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int addInfo(ActivityDO activity) throws DataAccessException {
    	if (activity == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert("MS-ACTIVITY-ADD-INFO", activity);

        return activity.getId();
    }

	/**
	 *  Update DB table <tt>makeploy_activity</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_activity set STATE=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (ID = ?)</tt>
	 *
	 *	@param state
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateStateById(String state, int id) throws DataAccessException {
        Map<String,Object> param = new HashMap<String,Object>();

        param.put("state", state);
        param.put("id", new Integer(id));

        return getSqlMapClientTemplate().update("MS-ACTIVITY-UPDATE-STATE-BY-ID", param);
    }

	/**
	 *  Update DB table <tt>makeploy_activity</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_activity set STATE=0, GMT_MODIFIED=CURRENT_TIMESTAMP where (type = ?)</tt>
	 *
	 *	@param type
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int resetStateByType(String type) throws DataAccessException {

        return getSqlMapClientTemplate().update("MS-ACTIVITY-RESET-STATE-BY-TYPE", type);
    }

	/**
	 *  Delete records from DB table <tt>makeploy_activity</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from makeploy_activity where (ID = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteActivityById(int id) throws DataAccessException {
        Integer param = new Integer(id);

        return getSqlMapClientTemplate().delete("MS-ACTIVITY-DELETE-ACTIVITY-BY-ID", param);
    }

	/**
	 *  Update DB table <tt>makeploy_activity</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_activity set POSTER=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (id = ?)</tt>
	 *
	 *	@param poster
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateBannerById(String poster, int id) throws DataAccessException {
        Map<String,Object> param = new HashMap<String,Object>();

        param.put("poster", poster);
        param.put("id", new Integer(id));

        return getSqlMapClientTemplate().update("MS-ACTIVITY-UPDATE-BANNER-BY-ID", param);
    }

	/**
	 *  Update DB table <tt>makeploy_activity</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update makeploy_activity set TYPE=?, STATE=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (TITLE = ?)</tt>
	 *
	 *	@param type
	 *	@param state
	 *	@param title
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateUnion(String type, String state, String title) throws DataAccessException {
        Map<String,Object> param = new HashMap<String,Object>();

        param.put("type", type);
        param.put("state", state);
        param.put("title", title);

        return getSqlMapClientTemplate().update("MS-ACTIVITY-UPDATE-UNION", param);
    }

	/**
	 *  Delete records from DB table <tt>makeploy_activity</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from makeploy_activity where (TITLE = ?)</tt>
	 *
	 *	@param title
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteHomeUnion(String title) throws DataAccessException {

        return getSqlMapClientTemplate().delete("MS-ACTIVITY-DELETE-HOME-UNION", title);
    }

	/**
	 *  Query DB table <tt>makeploy_activity</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select count(1) from makeploy_activity where ((TYPE = 8) AND (STATE = 1))</tt>
	 *
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int countUnion() throws DataAccessException {


	    Integer retObj = (Integer) getSqlMapClientTemplate().queryForObject("MS-ACTIVITY-COUNT-UNION", null);

		if (retObj == null) {
		    return 0;
		} else {
		    return retObj.intValue();
		}

    }

	/**
	 *  Query DB table <tt>makeploy_activity</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from makeploy_activity where (TITLE = ?)</tt>
	 *
	 *	@param title
	 *	@return ActivityDO
	 *	@throws DataAccessException
	 */	 
    public ActivityDO selectByTitle(String title) throws DataAccessException {

 
        return (ActivityDO) getSqlMapClientTemplate().queryForObject("MS-ACTIVITY-SELECT-BY-TITLE", title);

    }

}